evylang/evy

frontend/index.css
frontend/index.js

Add confetti easter egg, display round divs (confetti) when source code
contains substring confetti.

Add confetti easter egg

---

frontend/index.css
frontend/index.js

Update Easter egg. The intention was to update this interactively in a
coding session with some kids, but we ran out of time before we got to
it, so tune the current Easter egg and keep it🐣.

frontend: Update Easter egg

---

docs/syntax_by_example.md
docs/syntax_grammar.md

This doc update is a result of a bodged merge to master and has already
been reviewed previously 🙀.

docs: Update evy's grammar and examples

---

Makefile
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/errorstrings.go
pkg/parser/parser.go
pkg/parser/parser_literal.go
pkg/parser/parser_test.go
pkg/parser/type.go

Improve test coverage and error messages, where error messages refer to evy
parse errors.

parser: Improve test coverage and error messages

---

pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Update parseAssignmentStatment for index and dot expression as assignment
target.

parser: Update parseAssignmentStatment for index and dot

---

frontend/index.css
frontend/index.html
frontend/index.js

- Fix output height
- Fix indentation at the end of sample code
- Change sample code circle color to "red"

forntend: Tweak layout and sample code

---

pkg/evaluator/evaluator.go
pkg/wasm/main.go

Fix yielding as a regression bug has crept in PR67, commit aba3e29.
When running evy program:
for i := range 0 100 0.1
clear
dot i 50
sleep 0.01
end
func clear
color "white"
move 0 0
rect 100 100
end
func dot x:num y:num
color "red"
move x y
circle 10
end
The following error message shows up in the JS console and stops execution:
evy.wasm:0x4b39d Uncaught RuntimeError: unreachable
at asyncify_stop_unwind (evy.wasm:0x4b39d)
at tinygo_rewind (evy.wasm:0x4ae81)
at (*internal/task.Task).Resume (evy.wasm:0xa383)
at runtime.scheduler (evy.wasm:0x2e5f8)
at go_scheduler (evy.wasm:0x33835)
at go_scheduler.command_export (evy.wasm:0x4b237)
It seems that passing Yield as a stand-alone function rather than as
Interface implementation fixes this issue.

wasm: Fix yielding

---

pkg/evaluator/scope.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/scope.go

Implement anonymous variable `_` which cannot be read and only be
declared in function or event handler parameters. In a for loop prefer
a range statement without assignment.

parser: Implement anonymous variable `_`

---

Makefile
frontend/samples/animate.evy
frontend/samples/dot.evy
frontend/samples/draw.evy
frontend/samples/echo.evy
frontend/samples/rand.evy
frontend/samples/sliders.evy
main.go

Implement `evy fmt` command via parser.Program.Format() and add it to
Makefile for formatting and CI checks.
While at it clean up evy CLI tool a little bit.

main: Add `evy fmt` command

---

main.go

Fix up various unrelated small-ish issues overlooked review comments in
evy cli (main.go) from PR95, "add formatting". Sneak in an error rename
and global error variable alphabetical reorder.
Sincerest apologies for overlooking this!
Link: https://github.com/foxygoat/evy/pull/95

main: Fix overlooked review comments in evy cli

---

frontend/index.js
frontend/samples/samples.json
pkg/wasm/main.go

Refactor index.js by adding a few section comments, moving all globals to
the top and slightly reordering some functions. Rename `OnStopped()` to 
`AfterStop()`. Remove two unused exported functions. There are no
functional changes.
Add slider event sample

frontend: Refactor JS

---

Makefile
frontend/index.js
frontend/samples/games/tictactoe.evy
frontend/samples/games/tictactoetext.evy
frontend/samples/samples.json

Add a text based and a convas/mouse version of TicTacToe.
Allow for `"unlisted"` samples.
Links:
https://evy-lang--135-hik6n21b.web.app#tictactoetext
https://evy-lang--135-hik6n21b.web.app#tictactoe

samples: Add tictactoe

---

main.go

Add --skip-sleep flag to the evy cli so that we can run tests and
formatting faster. This flag has been created in the context of the
doctest.awk script.

cli: Add --skip-sleep flag

---

docs/builtins.md

Add builtin documentation for the string section.
The following list shows the new sections in context.
- ✅ I/O
- ✅ Types
- ✅ Map
- ✅ Program Control
- ✅ Conversion
- ✅ Error
- 👉 String
- ⬜️ Random
- ⬜️ Math
- ⬜️ UI
- ⬜️ Event Handlers
---
https://github.com/foxygoat/evy/blob/builtin-strings/docs/builtins.md#string
Current WIP:
https://github.com/foxygoat/evy/blob/builtin-wip/docs/builtins.md

docs: Add builtin docs for string functions

---

docs/builtins.md

Add builtin documentation for maths and random functions.
The following list shows the new sections in context.
✅ I/O
✅ Types
✅ Map
✅ Program Control
✅ Conversion
✅ Error
✅ String
👉 Random
👉 Math
⬜️ UI
⬜️ Event Handlers
---
https://github.com/foxygoat/evy/blob/builtin-math/docs/builtins.md#random
Current WIP:
https://github.com/foxygoat/evy/blob/builtin-wip/docs/builtins.md

Add builtin documentation for maths functions

---

pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Fix whitespace issue in type assertions and dot selectors.

parser: Fix white space issues

---

docs/spec.md

Update spec with valid variable and function naming. Add short
description on anonymous parameters `_`.

docs: Update spec with func and var naming

---

docs/spec.md

Revise spec contents on operators, whitespace and functions. The context of
these changes is as follows:
✅ Intro
✅ Evy syntax specification
✅ Comments
✅ Types
✅ Variables and Declarations
✅ Zero Values
✅ Assignments
✅ Copy and reference
✅ Scope
✅ Strings
✅ Arrays
✅ Maps
✅ Index and Slice
✅ Operators and Expressions
✅ Precedence
✅ Whitespace
✅ Functions
✅ Variadic functions
👉 Break and Return
👉 Typeof
👉 Type Assertion
👉 Run-time Panics and Recoverable Errors
👉 Execution Model and Event Handler
👉 Runtimes
---
Review link: https://github.com/foxygoat/evy/blob/spec-revision-4/docs/spec.md#break-and-return
After this PR I want to create one more cleanup PR replacing italics with
bold for technical terms. This leaves italics for emphasising ordinary words
and seems to better highlight the …

docs: Revise last section of spec contents (4/4)

---

docs/builtins.md
docs/spec.md

- Title-case all titles in spec
- Change italics to bold in spec and builtins
Add some typo fixes and minor improvements on various spec sections.
---
Review link: https://github.com/foxygoat/evy/blob/polish-spec/docs/spec.md

docs: Polish language specification

---

Makefile
main.go
pkg/assert/assert.go
scripts/gencmd.awk
scripts/gengodoc.awk
scripts/tocgen.awk

Improve godocs for evy command in main.go.
Auto-generate evy usage message and follow guidelines on:
https://go.dev/doc/comment
Docs can be viewed by pulling this branch and running:
go run golang.org/x/pkgsite/cmd/pkgsite@latest -open .

godoc: Improve on existing godocs

---

frontend/samples/animate/stringart.evy
frontend/samples/games/hanoi.evy
frontend/samples/games/tictactoe.evy
frontend/samples/games/tictactoetext.evy
frontend/samples/interact/ellipse.evy
frontend/samples/samples.json

- CameCase all evy functions and variables
- Update evy Hanoi sample with gameover check
- Add Cam's stringart animation

samples: CamelCase and add stringart

---

README.md
frontend/index.html

Add link to sponsorship page to evy website and to README.
---
See here: https://github.com/evylang/evy/tree/sponsor#readme

docs: Add link to sponsorship page

---

Makefile
docs/release-notes/v0.1.0.md

Add v0.1.0 release notes which should trigger the v0.1.0 release on
github. Keep the release notes short and sweet.

docs: Add v0.1.0 release notes

---

firebase/firebase.json

docs: Add firebase rewrite config to research paper for ICEET 24: evy-2401.pdf
Link: https://raw.githubusercontent.com/evylang/evy/v0.1.25/docs/papers/evy-2401.pdf
Link: https://www.wrfconference.com/event/index.php?id=2152733
---
This change has been deployed to https://evystage.dev/evy-2401.pdf

docs: Add firebase rewrite config to evy-2401.pdf

---

frontend/discord/img/favicon.png

Add missing favicon to discord subdomain. This shall teach me a lesson. Never resolve as author.
:moneybag: .

frontend: Add missing favicon to discord subdomain

---

main.go

Add a `compile` command to the CLI that is hidden, like the `tokenize`
and `parse` commands. `compile` outputs the bytecode for the evy program
specified on the command line (or stdin). It is intended for debugging
the compiler and for deeper understanding of what the bytecode for a
program looks like.

cli: Add hidden "compile" command to CLI

---

docs/usage.md
frontend/docs/usage.html

Update usage documentation to reflect that we now can create graphics with CLI
tool using the `--svg-out` flag.

docs: Update usage documentation

---

frontend/lab/samples/intro/move.evy
frontend/lab/samples/intro/var.evy
frontend/lab/samples/intro/welcome.evy

Tweak samples, removing one typo and adding a message to another.

lab: Tweak samples

---

frontend/lab/samples/loops/hsl.evy

Add HSL color picker to the loops sample for students to better understand HSL
color values. Inspired by Josh Comeau's work.
link: https://www.joshwcomeau.com/css/color-formats/#hsl-4

lab-site: Add HSL color picker to the loops sample

---

frontend/lab/samples/intro/var.htmlf
frontend/lab/samples/loops/welcome-loops.htmlf

Tweak the wording of a couple of notes in the labs. Ensure the "Don't run this
code" remark comes first. Add some bold to the intro slide of lab 2 and use the
definitive article "the" with Welcome to _the_ Loop Lab.

lab-site: Tweak the wording of a couple of labs

---

README.md

Fix typo in reference to ckas, he emailed me asking to please fix it.

docs: Fix typo in reference to ckas
