docs/syntax_by_example.md
docs/syntax_grammar.md

This is an attempt at "docs driven development".
I started off by writing what I think `evy` should look like which
became [`syntax_by_example.md`](https://github.com/foxygoat/evy/blob/docs-ini/docs/syntax_by_example.md). From there I tried to formalise
the syntax with a grammar taking many cues from the Go spec,
see [`syntax_grammar.md`](https://github.com/foxygoat/evy/blob/docs-ini/docs/syntax_grammar.md).
I think I will leave this PR that's now ready for review open
while trying to implement the compiler.

docs: Initialise evy's syntax grammar and examples

---

Makefile

Fix CI for `make firebase-public`. The `firebase-public` target depends
on the `tiny` target which runs `tinygo`. Tinygo requires a `go`
installation, in specific the `GOROOT` environment variable. Having go
not explicitly installed has been the cause of recent CI failures.
Add `go-version` target, which runs `go version` to ensure go is
downloaded and installed via hermit. Have targets `tiny` and
`test-tiny` depend on it.

github: Fix CI

---

Makefile
docs/syntax_grammar.md
frontend/index.html
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/scope.go
pkg/evaluator/value.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

Initialise parser and evaluator packages and wire them through all the
way to the frontend. Variable declaration via inference or type
declaration, as well as calls builtin function `print` with a variadic
number of arguments as literals or variables is possible now.
Tweak the frontend to actually print something with the initial demo
code.
Just like the lexer, many cues are taken from Thorston Ball's
Interpreter book source code.
Link: https://github.com/juliaogris/monkey

go: Initialise parser and evaluator

---

pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_literal.go
pkg/parser/parser_test.go
pkg/parser/parser_type.go
pkg/parser/type.go

Implement composite literal - array and map - parsing. Add insertion
order field to map for deterministic map printing and testing. Improve
error messages and type formatting to be more easily read and
understood.
The tests are a bit wanting, there is another PR in the works that improves on
error messages and test coverage and it was a bit too much effort to bring
it in before this one.

parser: Implement composite literal parsing

---

pkg/parser/parser.go
pkg/parser/parser_literal.go
pkg/parser/parser_test.go
pkg/parser/scope.go

Add scoped typed analysis to declarations, ensuring that variables or
parameters do not get redeclared in same block. Variables may be
re-declared in inner scope of a new block with a new type which does not
affect the outer scope. Add detailed tests for various scenarios.
As the parser will also take care of type analysis this is a necessary
addition and patches a whole in the previous global type analysis for
redeclaration.
Add a minor test refactor for parse error assertions

parser: Add scoped typed analysis to declarations

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/scope.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_literal.go
pkg/parser/parser_test.go
pkg/parser/scope.go

Implement return statements in ast, parser and evaluator. With this we
can more carefully test valid scoping in the evaluator.
Add pointer to FuncDecl in FuncCall node for easier evaluation.

go: Implement return statements

---

pkg/parser/parser.go

Fix typos in parser, changing `statment` to `statement`.

parser: Fix typos

---

main.go
pkg/evaluator/evaluator.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/main.go

Refactor builtins, such that parser package doesn't have any default
builtins other than for testing. Builtins need to be provided to parser
by caller. This ensures builtins are always only defined in one place.

go: Refactor builtins

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Add assignment parsing and assignment AST node. Extract parseAssignable
from parseTerm to reuse here. This will be extended by indexed and
field selector expressions. Rework String() method for Node type
Var, so that it works better in errors messages.
Add assignment evaluation: assignment nodes only update scope for
existing variables.

go: Add assignment evaluation and parsing

---

docs/syntax_grammar.md

Update grammar to enforce at least one statement in blocks. This means
each function declaration, if statement, while statement etc. need to
have at least one statement in the inner block. Like in Go's "variable
declared but not used" error message we want to catch accidental
omissions and limit the set of "valid programs" to provide more guide
rails.
The parser will be updated in a follow up PR.
While at it, reorder the production rules in the grammar to flow more
naturally from higher order constructs, to single line statements,
expressions and TERMINALS.

docs: Enforce at least one statement in blocks

---

frontend/index.html
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Add if statement parsing and evaluation - this is a pretty straight
forward PR, with only  minor refactors around BlockStatment parsing and
bool constants during evaluation.

go: Add if statement parsing and evaluation

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/scope.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/parser_type.go
pkg/parser/type.go

Implement while statement parsing and evaluation by reusing conditional
Block execution from If-statements parsing and evaluation and factor
out shared code.
Fix various bugs that popped up while implementing while statements:
- evaluator: Fix control flow for conditional return statements
- evaluator: Set variable value in correct scope
- parser: Intern basic parser types

Implement while statement parsing and evaluation

---

pkg/evaluator/evaluator.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/scope.go
pkg/parser/type.go

Harden return statements such that there is an error when there is
unreachable code after a return statement or a return statement is of
the wrong type.

parser: Harden return statements

---

.golangci.yaml
main.go
pkg/assert/assert.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/scope.go
pkg/evaluator/value.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/scope.go
pkg/parser/type.go
pkg/wasm/main.go

Crank up the linting settings so that linter runs in stricter mode and
catches more errors, before the codebase gets too big. Disable quite a few
annoying linters.

go: Crank up the linting settings

---

Makefile

Fix continuous deployment for master branch which broke with the recent
firebase deployment refactor. It seems that the service account used in
GitHub actions does not have enough permissions for generic Firebase
deploy, but needs to be restricted to `--only hosting`.

github: Fix continuous deployment for master

---

pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Add unused var check reporting an error if declared variable is never
used. This feature was yet again borrowed from go and piggy backed on
the scope data structure.
Refactor `validateVar` to `validateVarDecl` as it seems the more
appropriate name.

parser: Add unused var check

---

.github/workflows/cicd.yaml

Fix CI setup for master build, such that PR deploy is only executed on
CI run triggered by PR events. Master/prod deployment is executed as
part of the release job.
This is a bug as a result of the recent firebase deployment refactor.

github: Fix CI setup for master build

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/scope.go

Implement break statement in parser and evaluator ensuring it is only
used inside a loop. Use scope to keep track of enclosing AST node and
ensure that break's scope is within a loop (while) node's scope.
Implement unreachable code with block.AlwaysTerminates method on block.
Fix bare returns in evaluator as they accidentally got ignored and
didn't stop execution. This became apparent when thinking about breaks
in evaluator.
Also, fix AlwaysReturns method on While blocks. Loops may at times never
have their body executed so can _never_ always return.

go: Implement break statement

---

pkg/parser/expression.go

Rename `PREFIX` to `UNARY` in precedence enum. This has been an oversight
when renaming prefix to unary and infix to binary earlier on during the
Pratt parser implementation.

parser: Rename PREFIX to UNARY in precedence enum

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Add expression evaluation for basic types, including arithmetic operations,
logical operations, comparison operations, string concatenations, unary
operators and grouping with (). Still outstanding are all array and map
operations.

evaluator: Add expression evaluation for basic types

---

.golangci.yaml
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Add map and array literals to evaluation. We should have done this a
while back. Oversight.
---
Only the last commit is relevant of this PR, It depends on #37 to be
merged first (too many conflicts).

evaluator: Add map and array literals

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/scope.go
pkg/evaluator/value.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser_test.go

Add index and dot expression evaluation in evaluator, similar to binary
expression evaluation.
Change Array.Elements and Map.Order to pointer. This is another preparatory
step for proper array and map manipulation so that two variables may
reference the same array or map and if one gets updated the other one will
get updated too.
Rework scoped Value updates such that instead of replacing the value in the
scope on assignment with scope.set(name, newValue), we now update the Value
field with scope.get(name).Set(newValue)
---
The first three commits are covered by PRs #37 and #38 .

evaluator: Add index and dot expression evaluation

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/type.go

Add array concatenation for `+` operator. Ensure a copy of both operands is
made.
Fix parse error for array concatenation with empty arrays.
---
Only the last two commits of this PR are relevant. The rest depends on merging PRs 36-39.

evaluator: Array concatenation

---

Makefile
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Fix `any`'s wrapping `any`'s so that `any` only ever contains a
non-`any` type. We have added two test cases that failed before the code fix.
Sneak in a `make ci` dependency reorder so that linter errors surface earlier.

eval: Fix any's wrapping any's

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go

Add slice parsing and evaluation for array and string. Ensure copy is made of array
elements when slicing. Dis-allow string indexing on left side of assignment:
s := "abc"
s[0] = "ABC" // doesn't make sense.

go: Add slice expression

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/ranger.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Add `for` statement parsing according to grammar.
for_stmt   = "for" ident := "range" expr [ expr [expr]]
statements
"end" NL .
Range Expression can be an expression evaluating to a string, a map or
an array or it can consist of 1 to 3 numbers forming a StepRange.
Add 2 new AST nodes: `For` and `StepRange`. Fix up previous for loop tests
that now fail because of unused variable errors in parser package.
Add `for ... range` loop evaluation using the new AST nodes `for` and `stepRange`.
In order to properly capture the loopVariable, e.g. `x` in `for
x := range [1 2 3]` introduce the creation of a zeroValue from
a *parser.Type in evaluator.

Add for ... range loop parsing and evaluation

---

pkg/evaluator/evaluator_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Fix double index in target of assignment statements:
a := [[1 2] ([3])]
a[0][0] = 1
Fix by looping until next token is not a `[` or `.` any longer.
Also add test to evaluator ensuring we are evaluating correctly.
Fix missing isUsed flagging for indexed array

parser: Fix double index in assignment

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Fix assignment for new map key for statements like:
m := {}
m.a = 1
This previously errored with "no value for key a". Now treat reading map
entries and assigning them separately. If entry doesn't exist yet
create one with Zero value for assignment target.

evaluator: Fix assignment for new map key

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

Add builtin function `del` for entry removal from map:
del {a: 1} "a" // {}
Add builtin function `has` for entry existence check in map:
has {a: 1} "a" // true

evaluator: Add map builtins `has` and `del`

---

docs/syntax_by_example.md
docs/syntax_grammar.md

Update docs for whitespace. While at it, remove a bunch of duplicated
sections in grammar. We are now making horizontal whitespace `WS`
significant in certain places which allows us to remove the somewhat
awkward array and map typing in favour of derived and inferred types
for literals.
Remove `term` from grammar as it is not used in code, we only work with
expression. Introduce `<- ->` and  `<+ +>` tokens to annotated
whitespace inside grammar: expressions in expression lists, such as
function calls or array elements may not contain whitespace, as
whitespace is used as list separator.
Invert types so that types read as variables are being access:
m:[]{}string
m[0].name = "Joe"
Also add note on pass by reference for maps and arrays and pass by value
for string, num and bool.
---
For …

docs: Update docs for whitespace and inverted types

---

.github/scripts/app_token
.github/workflows/cicd.yaml
.goreleaser.yaml
Makefile

github: Commit brew formula on release
Automatically commit homebrew formula to
https://github.com/foxygoat/homebrew-tap when we create an `evy`
release. This allows mac users to install `evy` with
brew tap foxygoat/tap
brew install evy
`goreleaser` does the heavy lifting of creating the brew formula and
committing it, all configured in .goreleaser.yaml. However, creating a
GitHub token that has the privileges to push to another foxygoat repo
is tricky. Encapsulate the logic for creating a temporary, elevated
privileges GITHUB_TOKEN in script .github/scripts/app_token.
In the background we have created a new GitHub App to work as a "Service
Account" for cross-repo automation. It is only used on the foxygoat
GitHub org and it is called boxygoat (foxygoat bot). We have created
org wide …

github: Commit brew formula on release

---

.github/workflows/cicd.yaml
Makefile

Disable `app_token` script and use marketplace action 
`peter-murray/workflow-application-token-action@v1`
to create a temporary App `installation_token`.
This seems to work. 
Let's see if we can get brew formula update on merge to master and 
then circle back to work out the difference between this action and
our `app_token` bash script.

github: Disable app_token script and use marketplace action

---

.github/scripts/app_token
.github/workflows/cicd.yaml
Makefile

Fix `app_token` script by using `openssl enc -A -base64` instead of
`base64` because `base64` adds linebreaks on linux but not on mac. The
flag to change this doesn't work on mac.
Reinstate usage on with `make release` and remove node based third-party
app. We had only temporarily changed this to see if the rest of the
brew formula update process in repo foxygoat/homebrew-tap would work.

github: Fix app_token script

---

pkg/evaluator/evaluator_test.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexer/token.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Update lexer to emit single WS token for horizontal whitespace.
Implement whitespace sensitivity in parser: 
1. Disallow whitespace after unary operator 
2. Disallow whitespace within the expressions of a list:
- argument list of function call
- elements of an array literal
- values of map literal 
3. Regardless of context, allow whitespace within (), [] and {}

parser: Implement whitespace sensitivity

---

frontend/index.css
frontend/index.html
frontend/index.js
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/wasm/main.go

Initialize graphics primitives: move, line, rect, circle, color and
width (line width). Refactor DefaultBuiltins() function to take
a Runtime struct with graphics primitives provided.

graphics: Initialize graphics primitives

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go

Add join and sprint functions for easier string manipulation. Sprint, Join
and Print function have similarities for so they were refactored to use the
same underlying `join(args, sep) string` function in the same commit.
Join joins the string representations of the elements of an array with the
specified separator:
join [1 "a" true] ", " // 1, a, true
`sprint` concatenates the arguments given with a space separator, like
`print`, but returns a string rather than printing to a specified output
location. Unlike print it does not add a newline at the end as this seems
to be a more likely use case - to be seen and changed if deemed bad.

builtin: Add join and sprint functions

---

docs/syntax_grammar.md

Fix off-by-one error in example and while at it remove extra whitespace.
This has been reported by christof.kaser@gmail.com
Thanks @chkas

docs: Fix off-by-one error in example

---

frontend/index.css
frontend/index.html

Fix styles for iPad, the output was dim grey on the right. Also, turn
off change `i` being spell-corrected to `I`.

frontend: Fix styles for iPad

---

pkg/evaluator/evaluator_test.go

Add test ensuring func params can be reassigned - as I thought this was
a bug, but it turns out it was not.

evaluator: Add test ensuring func params can be reassigned

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go

Add new builtins. `split str sep` splits string into array of strings on
separator, using go's strings.Split and colour is a synonym for the
color function.

builtins: Add split and colour builtins

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Fix variable initialisation for inferred declaration and parameter
passing from another variable. Previously we would just use the same
value as the underlying variable which resulted in values of bath
variables changing even when only one was updated.
All newly added tests accept for `TestAssign3` failed prior to this fix.

evaluator: Fix variable initialisation

---

frontend/index.css

It seems ios creates some custom styles for disabled textareas. Fix
found on Stackoverflow.
Link: https://stackoverflow.com/a/23511280

Tweak CSS to make output look less faded on ios

---

main.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/main.go

Rework evaluator scopes so that they are part of the evaluator state.
A scope is in essence a linked list to it's outer scope so the data
structure can directly be used as a "stack" to push and pop scopes where 
needed. This work was initially done to re-work the evaluator execution
model so that we can react events such as OnClick and "step" through the
evaluation. However, we will explore this via channels next and keep the
actual execution call stack as is for now.

evaluator: Refactor scopes

---

frontend/index.html
frontend/index.js
pkg/wasm/main.go

Rework evy-evaluation to be hoisted on main rather than the separately
exported `evaluate` function. Some things, such as time.Sleep and
fmt.Sprintf only get properly initialised if the main*() function is
the entry point to the wasm code.
Additional, we had to solve to problem of having a JS function
returning a string in memory - we've done this in a hacky way by
returning Ptr and Length in separate function calls.
In preparation remove Lex and Parse button and wasm bindings.

all: Rework evy-evaluation to be hoisted on main

---

frontend/index.js
pkg/evaluator/builtin.go

Add the builtin `sleep` function: `sleep 1` sleeps for one second, 
`sleep 0.001` sleeps for one milli second. Now that we have wasm
hoisted on the main() go function we can just map to Go's sleep
function which panic'ed before.

evaluator: Add builtin sleep

---

pkg/parser/parser.go
pkg/parser/parser_test.go

Error on function redeclaration, including builtin functions. Before we
would just let new functions override existing functions which is
pretty confusing, err early err often.

parser: Error on function redeclaration

---

frontend/index.js
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/wasm/main.go

Implement stop in frontend by turning the Run button into a Stop button
during execution. For this we also need an onExit callback into JS from
go when execution finishes so that the button label gets reset.
Additionally we need to occasionally yield to JS event processing via a
`time.Sleep` in the evaluator code. This operation is abstracted via
the Yielder interface.
Execution is stopped in Eval if the Stopped flag is set, which gets set
on click via the exported Go function stop(). The access to the stop
flag is not synchronised, but as JS is single threaded so we don't need
to worry about it.
In a preparatory commit refactor evaluator and builtins so that there is 
a separate `NewEvaluator` function and `e.Run` method. This allows for
`wasm/main.go` to hold an evaluator as global …

all: Implement stop

---

pkg/evaluator/evaluator.go
pkg/evaluator/value.go

Tighten error handling with panics rather than returning false or nil so
that we can track down errors more easily in when they are a result of
internal coding errors.

evaluator: Tighten error handling with panics

---

Makefile
pkg/evaluator/evaluator.go
pkg/wasm/main.go

Fix memory corruption bug by adding `-stack-size` flag to 
`tinygo build` to fix memory corruption issues.
Revert sleeping yielder to interface
Link: https://gophers.slack.com/archives/CDJD3SUP6/p1676264760211069
Programs for testing:
Print circles
```
func target x:num y:num
move x y
colors := ["yellow" "gold" "orange" "red" "maroon"]
radius := 5
for c := range colors
color c
circle radius
radius = radius - 1
end 
end
target 40 40
```
Stop/Start non-sleeping endless loop
```
while true
print "🛼"
end
```
Stop/Start with sleep
```
for i := range 0 100 0.1
clear
dot i 50
sleep 0.01
end
func clear
color "white"
move 0 0
rect 100 100
end
func dot x:num y:num
color "red"
move x y
circle 10
end
```

make: Fix memory corruption bug by adding -stack-size flag

---

main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Update eventHandler parsing for parameters and bare return. Add builtin
eventHandler declarations for known even names and parameters.
In preparation fix for loop variable declaration validation and unify
parameter declaration validation with variable declaration validation.
This is part one of a two part PR. The second Part will add evaluation and 
wiring with frontend.

parser: Update eventHandler parsing for parameters and bare return

---

frontend/index.js
frontend/samples/dot.evy
frontend/samples/draw.evy
pkg/evaluator/evaluator.go
pkg/evaluator/value.go
pkg/parser/parser.go
pkg/wasm/main.go

Wire eventHandler to frontend so that when `on <event>` block appears in
evy code the corresponding frontend event triggers the execution of
that block. Currently implemented events: `down`, `up`, `move`, `key`.
Only `frontend:` and `all:` commits are relevant, the `parser:` commits are 
covered in #70 
Sample code
https://evy-lang--73-51oq7tbx.web.app#draw
```
on down x:num y:num
print "down" x y
end
on up
print "up"
end
on key c:string
print "key" c
end
```
simple drawing tool
```
d := false
width 1
on down x:num y:num
d = true
move x y
end
on up
d = false
end
on move x:num y:num
if d
line x y
end
end
```

all: Wire eventHandler to frontend

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go

Add printf and sprintf functions using Go's fmt.Sprintf (which now that we
hoist wasm code via main works 🚀). To allow for formatted printed of
numbers and bools add and `unwrap` function to value.go, unwrapping the
value of the Value interface implementation for basic types only.
In the process of creating printf, we discovered some missing unescaping in
the lexing stage as the goal is to keep string handling consistent with Go
and print "\n" as newlines. Fix it and improve error message for invalid
strings.
While at fix evaluator test output for multiline test cases and failed
tests.

builtin: Add printf and sprintf functions

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Add builtin functions `str2num` and `str2bool` converting strings to
numbers and bools. They set the evy global variables `err` and `errmsg` in
case of an error.
Rework builtins to take scope so that they can set `err` and `errmsg`.
Disallow redeclaration of builtin globals in parser.
For good housekeeping, fix inconsistent error messages in parser

evalutor: Add str2num and str2bool functions

---

frontend/index.css
frontend/index.html
frontend/index.js
frontend/samples/sliders.evy
pkg/evaluator/builtin.go
pkg/wasm/main.go

Add `on input id:string val:string` handler, so that evy can react to any
kind of input event, depending on how the frontend has wired it. By default
we have added and hidden to sliders in the index.html / DOM.
An example can be explored at
https://evy-lang--80-k6pkxs0k.web.app#show=.slider&source=samples/sliders.evy
In preparation change visibility of evy-widgets in dom via URL fragment.

all: Add `on input` handler

---

frontend/index.js
frontend/samples/animate.evy
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go
pkg/wasm/main.go

Add `on animate elapsedms:num` based on JS' window.requestAnimationFrame.
The parameter passed is the number of elapsed Milliseconds since the
animation started.
Rework yielding and make Sleep part of the runtime to fix flickering of
the animation.
https://evy-lang--81-9qbk365r.web.app/#animate
Aside: the initial sleep / dot animation is now flicker free too
https://evy-lang--81-9qbk365r.web.app/#dot

wasm: Add `on animate` syntax

---

frontend/index.js
frontend/samples/rand.evy
frontend/samples/strings.evy
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go

Add random number generation functions:
* `rand n` returns an integer in the half open interval [0,n)
* `rand1` returns an float64 in the half open interval [0,1)
Add string functions `upper`, `lower`, `index`, `trim`,
`startswith`, `endswith`, `replace`.
This functions are mapped to Go's math/rand package. It seems that
tinygo still requires seeding (tested).
Add a demos for clarity.
Minor bug fix for non 2xx source response: don't load random HTLM,
write error to console instead.
https://evy-lang--82-r0m72zv4.web.app/#source=samples/rand.evy&show=.read
https://evy-lang--82-r0m72zv4.web.app/#strings

builtin: Add `rand` and strings functions

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexer/token.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/operator.go

Add modulo operator to evy, which includes extending lexer, parser and
evaluator. As in other programming languages, use `%` symbol and give
the operator the same precedence as multiplication or division.

go: Add modulo operator `%` to evy

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/ranger.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Allow for statement without var declaration, e.g.:
for range 2
print "Hello"  // executed twice
end
This fell in place quite easily, however, the nesting might be deeper
than ideal - looking forward to feedback.

go: Allow `for` statement without var declaration

---

frontend/samples/animate.evy
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go

Allow for multiline array and map declarations so that it is easier to
declare large blocks of data. We want to get this in before we look
into `evy format` or syntax colouring as this might impact things.

parser: Allow for multiline array and map declarations

---

pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

Fix empty array bug mutating the GENERIC_ARRAY and GENERIC_MAP global
variable. These types are used when using the inferred declaration
a := []
At this point it is not clear which type or array a will be, but to say
it will be of type `any` is restricting it early. When we then assign a
typed array to a, e.g. with `a = [1 2]` a becomes an array of num. The
type is updated via type.Infer(), however, the Infer method mutated
itself (the GENERIC_ARRAY). Fix this by returning a copy.
This in turn made obvious that
for i := []
print i
end
caused an error, because we talk for ArrayRanging `array.Type.Sub`,
which we've now changed to `array.Type.Infer().Sub`

parser: Fix empty array bug

---

pkg/evaluator/evaluator_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Fix variadic parameter bug, where the variadic parameter gets added to
the scope in its original form rather than as an array of it. Before
we'd add for
func x n:num...
x with type `num` rather than `[]num` to the function body's scope.
Fix and add tests to evaluation and parsing.

parser: Fix variadic parameter bug

---

frontend/index.js

Fix read UI, so that it does not keep on grabbing the focus while
running. Ensure read input text field is shown.
Fix hashchange listener by attaching it to window, rather than document. We
now actually get a source change when updating the URL fragment.

frontend: Fix read textfield and hashchange

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

Prepare for `evy format` to print parse-error free source code 
in canonical way.
We will attach comments to the Stmt nodes in a follow up PR
when adding formatting, for this reason we introduce distinct
node for `FunCallStmt`, `InferredDeclStmt`, `TypedDeclStmt` and
`GroupedExpression` (expressions with `()`).
Remove the `Format` method from parser.Type to free up the Format
name purely for formatting and clean up its usage a little.

parser: Prepare for `evy format`

---

frontend/index.html
frontend/index.js
pkg/parser/ast.go
pkg/parser/operator.go
pkg/parser/parser.go

Keep UX in frontend for frequent sample switching. K
Keep go code tidy with ForStmt.String() fix and dead code removal.
This PR was shaved off #92 as there were a few too many unrelated fixes.

all: Keep UX and go code tidy

---

frontend/index.js
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/format.go
pkg/parser/format_test.go
pkg/parser/multiline.go
pkg/parser/multiline_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/main.go

Implement formatting in parser and wire in frontend prior to every
evaluation. Formatting was purposefully kept mostly to the
`parser/format.go` file.
This is feature complete formatting, the only outstanding work
is to add `evy format [-w] FILE...` to evy CLI.
Reformat sample code by running:
https://evy-lang--94-x5xuqzz3.web.app/#animate
https://evy-lang--94-x5xuqzz3.web.app/#dot
https://evy-lang--94-x5xuqzz3.web.app/#draw
https://evy-lang--94-x5xuqzz3.web.app/#echo
https://evy-lang--94-x5xuqzz3.web.app/#rand
https://evy-lang--94-x5xuqzz3.web.app/#sliders
https://evy-lang--94-x5xuqzz3.web.app/#strings
We had to hack around not using interfaces as map keys by converting them
`uinptr` to work around a tinygo-0.27.0 bug which has been fixed on 
dev, see gophers slack link for details. …

all: Implement formatting of evy code

---

pkg/parser/ast.go
pkg/parser/format.go
pkg/parser/format_test.go
pkg/parser/multiline.go
pkg/parser/multiline_test.go

Insert NL before `func` and `on` statements for function and eventhandler
declarations. Honour leading comments. Insert newline after func and event
handler declarations if directly followed by a stmt.

parser: Insert NL before `func`

---

.golangci.yaml
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/format_test.go
pkg/parser/multiline_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/main.go

Clean up error handling, using real go errors rather than overloading
the evaluator.Value interface of storing errors as part of the parse
state. Make parser private and attach all state to AST node program.
Reorder main.go for readability.
This is a pure refactor PR without any functional additions.

go: Clean up error handling and parser state

---

frontend/index.css
frontend/index.js

Styling:
- remove code ligatures
- ensure modal navigation dialogue is 5% transparent
JS:
fix minor navigation bugs

frontend: Cleanup various minor bugs

---

pkg/parser/format.go
pkg/parser/format_test.go

Fix two formatting bugs that rendered evy program un-executable but
required only minor source updates:
- escape `\n` in stringliterals with strconv.Quote.
Previously a literal newline was printed inside the string.
- ensure unary operators get formatted properly.
Previously `while !(check)` formatted to `while !check()`
Add test for the fixes and ensure tests failed previous to fix.

parser: Fix formatting bug

---

frontend/index.js

Fix comment for typo in `handleMobRun()`. This is a fixup for an
overlooked review remark.
Link: https://github.com/foxygoat/evy/pull/102#discussion_r1136467397

frontend: Fix comment

---

frontend/index.js

Remove focus from `read` input when program is stopped as a UX helper
that the program isn't running any longer.

frontend: Remove focus on stop

---

pkg/lexer/lexer.go
pkg/lexer/lexer_test.go

Fix string tokens for 2n backslashes before the closing `"` quotation
mark.

lexer: Fix string tokens for double backslash

---

frontend/courses/courses.json
frontend/courses/sample/tour/math.evy
pkg/evaluator/builtin.go

Add some essential maths functions. This has been again added on request
to allow for more interesting graphics, especially sin, cos, atan2.
Thanks @fcostin for the suggestion.

builtin: Add maths functions

---

frontend/courses/courses.json
frontend/courses/sample/animate/splashtrig.evy

@fcostin kindly donated this sample to the project using "a splash of
trig". I've user acceptance tested it with my daughter and she loved
it.
See: https://evy-lang--110-kz6wxu5z.web.app/#splashtrig

evy: Add splash of trig sample

---

main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/wasm/imports.go
pkg/wasm/main.go

Refactor evaluator.Runtime into interface as it appears to be the more
appropriate structure and works well with jsRuntime and cliRuntime. This
also allows for jsRuntime to track its own sleepingYielder.

evaluator: Refactor Runtime into interface

---

frontend/index.js
pkg/evaluator/evaluator.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/imports.go
pkg/wasm/main.go

Implement output UI initialisation from evy source code analysis:
* show/hide canvas if there are some/no drawing functions in evy code.
* show/hide read input text field
* show/hide sliders
Update the parser.Program ast node to expose `CalledBuiltinFuncs` which
determine UI changes. Include eventhandler implementation in code analysis.
Note: there is a race condition when navigating back/forwards between
stopping the program and reinstantiating wasmInst for formatting / ui initialisation of new code.
wasmInst is asynchronously set to undefined after the wasm
execution has finished and called afterStop function.

all: Implement output UI initialisation

---

.prettierignore
frontend/index.css
frontend/index.html
frontend/index.js
frontend/module/yace-editor.js

Add evy syntax colouring by implementing a custom highlight function for
lightweight JS code editor Yace. 
Copy all relevant Yace source files with minor tweaks into a single file 
`frontend/module/yace-editor.js` as we are not (yet) using a JS bundler.
Link: https://github.com/petersolopov/yace
Link: https://github.com/petersolopov/mdhl

frontend: Add syntax colouring

---

frontend/img/err-line.svg
frontend/index.css
frontend/index.html
frontend/index.js
frontend/module/yace-editor.js
pkg/evaluator/evaluator_test.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/wasm/imports.go
pkg/wasm/main.go

Highlight lines with evy errors in editor. This is done by finding the
correct token by its line and columns and adding the "err" CSS class to it.
It is becoming increasingly obvious that a more fully fledged web code
editor will be needed. Evy files with more than 700ish lines are starting
to get janky when editing. I could work around this by only updating the
relevant lines, but it all seems to get a bit to hacky.
housekeeping: Do a one-off lint pass with stylelint of CSS(requires node
to which I'm not yet ready to commit.)

frontend: Highlight lines with error

---

frontend/index.js
frontend/module/yace-editor.js

* Highlight first, not last error token in line
* Fix empty/delete-all editor bug

frontend: Fix editor buglets

---

pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/parser/parser_test.go

Fix empty string lit in middle of line. As we advance at the beginning
of reading string and then again when peekRune is `"` we overshoot for
empty strings `""`. Fix this be doing the outer advance only at the end
of the iteration.

lexer: Fix empty string lit in middle of line

---

pkg/parser/parser.go
pkg/parser/parser_test.go

Fix panic on nil token in error when overriding builtin function names.
This was noted when implementing `clear` which had a different
signature from the hand written clear in the samples. Add panic in
error appending for nil tokens so that we get traceable panics.

parser: Fix panic on nil token in error

---

frontend/index.js
frontend/module/yace-editor.js

Reset error highlight on start (run), so that the error highlight so
that we accurately display new errors or no errors if they are gone.
Previously errors only got reset if the line was updated which
incorrectly kept error line highlight for follow-on errors, e.g.:
x := "foo"  // line 1: 'x' declared but not used
print y     // line 2: unknown variable name 'y'
Fixed as
x := "foo"  // 💣 error remained: line 1: 'x' declared but not used
print x     // no error
Now all errors get reset.

frontend: Reset error highlight on start

---

frontend/courses/sample/animate/juggle.evy
frontend/courses/sample/animate/movingdot.evy
frontend/courses/sample/animate/splashtrig.evy
frontend/courses/sample/tour/events.evy
frontend/index.js
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Add `clear` to drawing functions as a builtin because it is very
commonly used. Use an optional second parameter to specify the clear or
background colour.

evy: Add `clear` to drawing functions

---

.golangci.yaml
frontend/courses/courses.json
frontend/courses/sample/draw/fill.evy
frontend/courses/sample/draw/linestyle.evy
frontend/index.js
frontend/module/yace-editor.js
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Add drawing style functions stroke, fill, dash, and linecap defined in
the same terms as HTML canvas styling, with the addition of `"none"`
for stroke and fill.
New examples:
- https://evy-lang--123-x8t7erj2.web.app/#linestyle
- https://evy-lang--123-x8t7erj2.web.app/#fill

evy: Add drawing style functions

---

frontend/courses/courses.json
frontend/courses/sample/draw/text.evy
frontend/index.js
frontend/module/yace-editor.js
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Add canvas text builtins `text`, `textsize`, `fontfamily`, and `font`.
Add new example #text. These new primitives are only concerned with
text and text styles on the evy output canvas.

evy: Add canvas text builtins

---

frontend/courses/courses.json
frontend/courses/sample/draw/poly.evy
frontend/index.js
frontend/module/yace-editor.js
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Add canvas poly builtin to draw polylines and polygons.
New sample:
https://evy-lang--125-ofi7tbe4.web.app/#poly

evy: Add canvas poly builtin

---

frontend/index.css

Fix pointermove event for mobile touch according to
https://stackoverflow.com/a/48254578
It seems that on mobile the browser captures pointermove events for its
own use (scrolling). This can be disabled with the CSS property
`touch-action: none;`. However, this is not preferable for
accessibility cases, so still allow pinch to zoom.
Tested on Android and iPad
The following sample now also works on mobile:
https://evy-lang--126-hesnlymh.web.app/#draw

frontend: Fix pointermove event for mobile

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go

Do not nest a function scope inside another function scope, since we do
not look up variables across function scopes. A function scope should be
based on the global scope only (and this includes handler scopes too,
which are just a function in disguise).
This program would print "2" instead of "1" as `f2` was traversing the
scope of `f1` when looking up `a` to print. It should skip `f1` and go
straight to the global scope:
a := 1
func f1
a := 2
f2
end
func f2
print a
end
f1

evaluator: Don't nest function scope inside other function scope

---

frontend/courses/courses.json
frontend/courses/sample/draw/ellipse.evy
frontend/index.js
frontend/module/yace-editor.js
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Add canvas ellipse drawing builtin to draw ellipse with
ellipse x y radiusX [radiusY [rotation [startDegree endDegree]]]

evy: Add ellipse drawing builtin

---

docs/syntax_grammar.md
frontend/courses/courses.json
frontend/courses/sample/games/hanoi.evy
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go

Implement short-circuiting of the AND and OR operators so that the
right-hand side is not evaluated if the result can be determined by the
left-hand side. For AND, this means left == false, since the whole
expression will be false regardless of what right is. For OR, this means
left == true, for the same reason.
Update the spec to say these operators perform short-circuit evaluation.
Add a Towers of Hanoi evy program with a new "Games" section in the
course. This program uses short-circuit evaluation to protect against
indexing an array out of bounds, hence its presence with this change.

evaluator: Implement short-circuit evaluation of AND/OR

---

docs/syntax_grammar.md

Clean up the spacing of the grammar and add missing period production
terminators. This changes nothing of substance, just cleanliness.

docs: Clean up grammar spacing, etc

---

frontend/index.js
frontend/samples/animate/ellipse.evy

Capture pointerleave event on canvas by using exact values `0` or `100`
for `x` or `y` to use as condition to stop animations, for example in
the interactive ellipse 🍉 sample. This addition was in response to
watching Mali play with the example and being confused with what it did
when leaving the mouse left the canvas.

frontend: Capture pointerleave event on canvas

---

frontend/index.js
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/expression.go
pkg/wasm/main.go

Add token location to evaluator errors and surface them in JS and UI.
In two preparatory commits remove the unused `eval.Error` type and
reword some sentinel errors in evaluator.

eval: Add token location to evaluator errors

---

main.go

The CLI runtime `Read()` function was returning the line read with the
trailing newline. This is different to how the browser/wasm
implementation works which does not include the trailing newline. This
makes for different behaviour when running an evy program with the
different runtimes.

main: Drop trailing newline in CLI read function

---

docs/syntax_grammar.md

Fix the grammar docs to specify that the variable declaration is
optional. This removes the assignment option as that is not implemented,
nor is it planned to be implemented.

docs: Fix grammar of for loops

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go

Fix the evaluation of the `break` statement so as to not break out of
more than one loop (`for` or `while`). We do this by turning a `Break`
`Value` into a `nil` `Value` when it is handled, breaking a loop.
Further outer loops will no longer break out.
Add tests for this case.

eval: Fix break to not break more than one level

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/lexer/lexer_test.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/errorstrings.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Use fmt.Sprintf where sensible - it was used before with the assumption
that tinygo doesn't support it (runtime error), but it turns out this
was only because we didn't use main() as mount point. While at it,
change all single to double quotes.

go: Use fmt.Sprintf where sensible

---

pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/format_test.go
pkg/parser/multiline_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Refactor parser private function order a little and break up newParser (bit long).
Move scope stack into parser state rather than passing it
around as parameters.

parser: Move scope stack to parser state

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/value.go

Remove the `ValueType` type in favour of `*parser.Type` to enable deeper 
type knowledge of composite types (arrays, maps) that do not have values.
The `ValueType` type only modelled an array or map but not the type of its
contents. If the composite value was empty, it was not possible to tell
what the full composite type was. This makes it impossible to properly do
type assertions.
An `Array` and `Map` now need to store the actual parser type within the 
value. The simple types can just return the parser "constants" for those 
types without needing any extra storage.
This adds a `None` `Value` implementation that is returned instead of
`nil` when an evaluation does not result in a value, making it a little
safer to use everywhere. One place, `evalConditionalBlock` still does
return a …

eval: Replace ValueType with *parser.Type

---

docs/syntax_grammar.md
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/format.go
pkg/parser/format_test.go
pkg/parser/parser.go
pkg/parser/type.go

Implement type assertions as defined in the spec in the parser as a new
AST node type and in the evaluator to evaluate that AST node. Implement
the `typeof` builtin so that type assertions can be used safely and robustly
over a range of types.
Update the spec to make `typeof` more specified in the value returned for
arrays and maps, and cover the special case of empty array and map
literals that do not yet have a subtype.
A couple of small bugs have been fixed were AST nodes for literals were
not fully constructed, and where types were not inferred deeply enough
in the case of array and map elements of arrays and maps.

parser/eval: Implement type assertions and typeof builtin

---

Makefile

Update the `NEXTTAG_CMD` command to identify when a release note has
been added in the latest master commit in `docs/release-notes/v*.md` and
extract the version from the filename. If that version is later than
what `NEXTTAG_CMD` would have used by default, use that version number
for the tag instead.
This allows creating a commit/PR with a new release note and have that
version get auto-tagged and released when merged to master.

ci: Support auto-versioning of major/minor versions

---

docs/syntax_by_example.md

Rework syntax by example to match the current state of evy. Remove
references to builtin functions which will be treated in a separate
document.
---
There will be a bunch of follow up commits, next probably builtins,
then spec and README.md. I'm trying to keep things digestible here and just do one file at a time. Diff is probably a bit useless, 💰 
Maybe easiest reviewed on branch:
https://github.com/foxygoat/evy/blob/docs/docs/syntax_by_example.md

docs: Rework syntax by example

---

frontend/module/yace-editor.js
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/parser/format_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/scope.go
pkg/wasm/main.go

Add `exit N` builtin function calling os.Exit(N) on the evy CLI and
terminating the wasm interpreter on the web. On the web for exit status
greater 0 a runtime error type output is generated pointing to the line
that caused the exit.
In preparation remove top level return statements which where a bit
weird to start with. And sneak in a re-parse for correct token location
after formatting and a builtin emptyDecl refactor.

evy: Add `exit` builtin function

---

pkg/evaluator/builtin.go

Fix rand seeding for tinygo 0.28.1. Go 1.20 automatically seeds its
random functions but tinygo hasn't caught up, so manually seed the
random function, but don't use the deprecated global random.Seed for
it, use the new rand.Source.

builtin: Fix rand seeding

---

Makefile

Optimise evy.wasm performance and size with `wasm-opt O3`. Empirically it
seems to reduce runtime of computationally intensive evy programs, such as
the Barnsley Fern by at least 40% and the evy.wasm file size by around 5%
while only taking a couple of extra seconds during the build - this seems
worth it! Thanks @camh- for the find.

make: Optimise evy.wasm performance and size

---

frontend/404.html
frontend/index.css
frontend/index.html
frontend/index.js
frontend/module/yace-editor.js

It seems that prettier 3.0.0 was just released and formats some things
differently by default, so reformat accordingly.
Also, change canvas default background from "transparent" to "white" and
add grid lines at 0 and 100 - as this has been useful in creating docs
and samples.

housekeeping: Reformat with new prettier, adjust UI funcs

---

.github/workflows/cicd.yaml
Makefile
docs/builtins.md
docs/syntax_by_example.md

Add builtins.md with docs for I/O builtin functions. In follow up
commits we will extend builtins.md with the following sections:
- Types
- Map
- Program Control
- Conversion
- String
- Random
- Math
- Error
- UI
- Event Handlers
Add a `doctest` target to the Makefile run with `make ci` checking for
non-dirty git status of the relevant markdown files.
Update github CI environment with the environment variable `TERM=vt100`.
Without this environment variable set `cls` fails and without that we
cannot run doctest on CI.
---
https://github.com/foxygoat/evy/blob/builtin-docs/docs/builtins.md
Current WIP:
https://github.com/foxygoat/evy/blob/builtin-types/docs/builtins.md

docs: Add builtins.md

---

docs/builtins.md
pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go

Add builtin function documentation for sections: types, maps, and
program control. The following list shows the new sections in context.
- ✅ I/O
- 👉 Types
- 👉 Map
- 👉 Program Control
- ⬜️ Conversion
- ⬜️ String
- ⬜️ Random
- ⬜️ Math
- ⬜️ Error
- ⬜️ UI
- ⬜️ Event Handlers
While drafting an example for `exit` it seemed that str2bool|num should
improve its error message format. It should quote its input string.
Added here.
---
https://github.com/foxygoat/evy/blob/builtin-types/docs/builtins.md#types
Current WIP:
https://github.com/foxygoat/evy/blob/builtin-wip/docs/builtins.md

docs: Add builtin docs for types, maps, prog control

---

docs/builtins.md

Add builtin documentation for sections: conversion and errors.
The following list shows the new sections in context.
- ✅ I/O
- ✅ Types
- ✅ Map
- ✅ Program Control
- 👉 Conversion
- 👉 Error
- ⬜️ String
- ⬜️ Random
- ⬜️ Math
- ⬜️ UI
- ⬜️ Event Handlers
Fix a couple of accidentally left of over whitespace in previous PRs.
---
https://github.com/foxygoat/evy/blob/builtin-strings/docs/builtins.md#conversion
Current WIP:
https://github.com/foxygoat/evy/blob/builtin-wip/docs/builtins.md

docs: Add builtin docs for conversion functions and errors

---

.github/workflows/cicd.yaml
.golangci.yaml
.prettierrc.json
Makefile
docs/builtins.md
docs/syntax_by_example.md
docs/syntax_grammar.md
firebase/firebase.json

Run prettier format checks on all file formats that prettier can format:
.js, .html, .css, .md, .json, .yaml. Simply update the prettier check
and format commands to run on the repo root rather than the frontend
directory (Makefile changes). Update all relevant files with
make prettier
Ensure checks are passing again with `make check-prettier`.
---
This is a mechanical PR using prettier in more places and fixing
formatting accordingly.

make: Run prettier format checks on all files

---

pkg/parser/format.go
pkg/parser/multiline.go
pkg/parser/multiline_test.go
pkg/wasm/imports.go

Remove tinygo v0.27.0 map hack, working around not being able to use
interfaces as map keys. tinygo v0.28.0 has fixed this bug so remove the
workaround.

parser: Remove tinygo v0.27.0 map hack

---

docs/builtins.md

Fix builtin typo for `linecap` to be consistent with other `Reference`
sections. This was due to a premature merge.

docs: Fix builtin typo for linecap

---

pkg/parser/parser.go
pkg/parser/parser_test.go

Fix bad unreachable code error on comments by only issuing the error if
the statement is not a comment (or an empty line).

parser: Fix bad unreachable code error on comments

---

pkg/parser/format_test.go
pkg/parser/multiline.go

Fix misplaced NL before function declaration. This is issue became apparent when
a := 1
b := 2
func fn
print "fn" a b
end
was reformatted to
a := 1
b := 2
func fn
print "fn" a b
end
now fixed.

format: Fix misplaced NL before func decl

---

Makefile
docs/builtins.md
scripts/toc.awk
scripts/tocgen.awk

Add ToC to builtins.md as an initial overview and end func docs with a
horizontal line for easier readability.
---
Preview: https://github.com/foxygoat/evy/blob/builtin-hsep/docs/builtins.md

docs: Add ToC and horizontal separators to builtins

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/scope.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/parser.go

Type empty array and map lit on assignment with type of LHS asignable
and as []any or {}any for inferred declaration.
a := []
print (typeof a) // before: [] now: []any
b:[]num
print (typeof b) // before: []num now: []num
b = []
print (typeof b) // before: [] now: []num
print (typeof []) // before: [] now: []
This seems to be more accurate and expected behaviour.
Fix the same behaviour for parameter passing and including for variadic
parameters.
Throw in a little bug fix for variadic args for good measure.

eval: Type empty array and map lit on assignment

---

pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/expression.go
pkg/parser/parser_test.go
pkg/parser/type.go

Fix typing of array concatenation expressions so that `[]+[true]` now
returns the correct `[]bool` type.
Before:
`print (typeof []+[true])` -> `[]`
Now:
`print (typeof []+[true])` -> `[]bool`

parser: Fix typing of array concatenation expressions

---

pkg/evaluator/evaluator_test.go
pkg/parser/expression.go
pkg/parser/parser_test.go

Fix function call parsing for arguments with index - maps, type assertions,
grouped expressions and arrays. We're here at a finicky bit of evy. Prior
to this PR we'd get a compile error for:
print {} []
error message:
line 1: unexpected whitespace before "["
Remove debug print in tests from previous PR.

parser: Fix function calls with indexed arguments

---

frontend/index.js
main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go

Add `panic` function that interrupts evaluations with a `PanicError`
which contains the panic message. It is up to the runtime to decide
what to do with it.
---
Here's an evy program to play with:
```
print "before panic"
panic "🙀"
print "after panic"
```
Link: https://evy-lang--178-2e7co2tu.web.app/#content=H4sIAAAAAAAAEysoyswrUVBKSk3LL0pVKEjMy0xW4gJTCkof5s9sAHIgKhLTSlKLYAq4AGoqMzw3AAAA

builtins: Add `panic` function 

---

Makefile
docs/builtins.md
docs/spec.md
docs/syntax_by_example.md

Revise spec contents on types and use evy and evy:output code fences.
The context of these changes is as follows although there have been
minor reformatting changes added to the later sections too.
✅ Intro
✅ Evy syntax specification
👉 Comments
👉 Types
👉 Variables and Declarations
👉 Zero Values
👉 Assignments
👉 Copy and reference
👉 Scope
👉 Strings
👉 Arrays
👉 Maps
👉 Index and Slice
⬜️ Operators
⬜️ Precedence
⬜️ Whitespace
⬜️ Functions
⬜️ Variadic functions
⬜️ Break and Return
⬜️ Typeof
⬜️ Type assertion
⬜️ Event Handler
⬜️ Errors
⬜️ Runtime
Add doctest for spec.md to Makefile and CI.

docs: Revise spec contents on types (2/4)

---

docs/builtins.md
docs/spec.md

Revise spec contents on operators, whitespace and functions. The context of
these changes is as follows:
✅ Intro
✅ Evy syntax specification
✅ Comments
✅ Types
✅ Variables and Declarations
✅ Zero Values
✅ Assignments
✅ Copy and reference
✅ Scope
✅ Strings
✅ Arrays
✅ Maps
✅ Index and Slice
👉 Operators and Expressions
👉 Precedence
👉 Whitespace
👉 Functions
👉 Variadic functions
⬜️ Break and Return
⬜️ Typeof
⬜️ Type assertion
⬜️ Event Handler
⬜️ Errors
⬜️ Runtime
Revise builtins intro to reference the `spec.md` and `syntax_by_example.md`.
---
- Only the last two commits of this PR are relevant, all others are covered by
previous PRs but to avoid merge conflicts / closed PRs / general chaos - I'll keep them here.
- Review Link: https://github.com/foxygoat/evy/blob/spec-revision-3/docs/spec.md#ope …

docs: Revise spec contents on types (3/4)

---

docs/builtins.md
scripts/doctest.awk

Fix the error handling of `doctest.awk` when running evy to output the 
error captured instead of the previous output captured. While fixing this,
capture stderr err from the command executed as that is often where error
output goes. And then close `/dev/stderr` for good measure.
Add an `expect_err` flag to go after the `evy` language marker used by 
doctest to denote that the evy program is expected to exit with an error.
In these cases, we do not report the error and instead capture the error
output to put in the `evy:output` block.
Update `docs/builtins.md` to add this `expect_err` flag to the `exit` 
builtin which exits with an error. This cleans up the output of
`make doctest` so it no longer reports an expected error.

docs: Fix and improve doctest error handling

---

scripts/doctest.awk

Use the POSIX awk syntax for deleting an array in doctest.awk instead of
the gawk syntax. Whoops.

docs: Use POSIX syntax for deleting array in awk

---

docs/builtins.md
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/parser.go

Rename runtime error to panic so that index out of bounds and similar
runtime errors appear like a panic. Then all unrecoverable runtime
errors are panics or internal errors (which should never occur). While
at it, fix the error message for missing closing quote of string
literals and improve on the error section in builtins.md. 
Add a section on using the `panic` builtin.
This is precursory work to finish off the last part of the spec revision,
including errors.

evaluator: Rename runtime error to panic

---

README.md
docs/README.md
docs/builtins.md
docs/spec.md
docs/usage.md
firebase/firebase.json

Tweak docs and add redirects from evy.dev:
- change chat on Slack to chat on Discord
- add a redirect to for evy.dev/play
- add a docs/README.md landing page

docs: Tweak docs and add redirects from evy.dev

---

main.go
pkg/lexer/lexer.go
pkg/lexer/lexer_test.go
pkg/lexer/token.go
pkg/parser/expression.go
pkg/parser/parser.go

Rework package, public type and function godocs for lexer package
according to new guidelines. While writing docs it became obvious that
we could remove several bits of this package make others private - less
documentation effort and commitment to maintain compatibility.
---
To view docs locally pull branch and run
go run golang.org/x/pkgsite/cmd/pkgsite@latest -open .

lexer: Rework godocs

---

main.go
pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/lexer/token.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/format.go
pkg/parser/format_test.go
pkg/parser/multiline.go
pkg/parser/operator.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go
pkg/wasm/main.go

Prepare for parser godoc revision by renaming some types and functions, making
others private and removing a few altogether. All these changes
came about by looking at the docs and asking: do I want to support this?
Does this make sense? 
I've started using the `revive` linter again, "a drop in
replacement for deprecated `golint`", which also covers missing godocs but
it isn't ready yet to be added to the CI flow. However, it has surfaced
a couple of other problems that have been addressed here. The main
reason I'm already cutting this as PR is because the prep work is
getting a bit big.
---
For a local review of the resulting godocs pull this branch and run
go run golang.org/x/pkgsite/cmd/pkgsite@latest -open .

docs: Prepare for parser godoc revision

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/expression.go

- Fix built-in len function for strings, especially for emojis
- Improve ErrVarNotSet error if funcs use variables that have not yet
been declared at call site.

all: Fix len func and improve errors

---

.github/workflows/cicd.yaml

Replace `boxygoatbot` with `evlangbot` credentials so that hopefully we can
release again. 🤞
This is trying to address the following failed CI release job:
https://github.com/evylang/evy/actions/runs/6419265641/job/17428830002

Replace boxygoatbot with evlangbot creds

---

frontend/module/yace-editor.js

Turn off auto-capitalise on mobile devices. The values were incorrectly set to
false rather than `"off"` and `"none"`.

frontend: Turn off auto-capitalise on mobile devices

---

frontend/index.css
frontend/index.html
frontend/index.js

- Remove autofocus from copy input to avoid virtual keyboard popping up
- Fix size and padding of evy-e in about dialog
- Hide sidebar when showing "About" dialog, to avoid flicker on close
- Fix sticky hover state on run button on mobile

frontend: Fix mobile style and UI buglets

---

pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

In yet another attempt to wrangle the complexities around assignability, shave
off a bunch of preparatory commits:
- Pre pare pkg/parser/types.go refactor by 
* moving `combineTypes` into it
* removing `sameComposite` in favour of inlining
- Add a missing godoc comment in parser
- Fix whitespace in tests

parser: Prepare assignability refactor

---

docs/spec.md
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go
pkg/parser/type_test.go

Refactor types.go to only use Equals and assignable methods for type. This
makes the code more readable and easier to maintain. Add a section on
assignability to the spec.
---
Only the last commit is relevant, the others are covered by #215.

parser: Refactor types.go

---

frontend/index.css
frontend/index.html
frontend/index.js
frontend/module/yace-editor.js

Improve initial loading user experience on slow networks by pre filling the
editor area with the Welcome example, fixing a load race condition and
showing a load dialog if the run button is clicked before the tool chain is
ready.
While at it fix a regression scroll bug for the example modal and add styling
for the runbutton active state to avoid the weird blue color on tap on
mobile.

frontend: Improve initial load UX on slow networks

---

pkg/evaluator/builtin.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/format.go
pkg/parser/parser_test.go
pkg/parser/type.go
pkg/parser/type_test.go

Rename UNTYPED_ARRY and UNTYPED_MAP to EMPTY_ARRY and EMPTY_MAP if they 
represent an empty array or map and to GENERIC_ARRAY and GENERIC_MAP if
they are used as generic parameters to builtins.
---
This PR is based on PR217. Only the last commit is relevant.

parser: Refactor UNTYPED_ARRY and UNTYPED_MAP names

---

docs/builtins.md
scripts/doctest.awk

Ensure awk exits with an error when there is an error in an evy code block.
Prior to this, an error was printed but awk still exited with 0 allowing CI
and `make doctest` to continue.
Emit a document line number when an error is reported to make it easier to
locate where the error is.
Change the tagging of evy code that is expected to exit with an error
from `evy expect_err` to `evy:err`. Update the builtins docs to use this
(and fix a misspelling at the same time that mismarked a block).

doctest: Exit with an error when errors occur

---

pkg/parser/ast.go

Reorder methods in ast.go, such that they all come straight after the
receivers type definition. Publich methods, alphabetically sorted come first,
then private methods.
This is a pure code movement - nothing added or removed. It is only made for
readability.

parser: Reorder methods in ast.go

---

pkg/parser/parser.go
pkg/parser/parser_test.go

There is a prepare step parsing all function signatures. If an error is
encountered in this stage, abort further parsing. This addresses a bug report
as covered in the added test.
Thank you @alecthomas for the report.

parser: Abort parsing for invalid function signatures

---

Makefile
README.md
docs/development/releasing.md
firebase/firebase.json

- Document release process.
- Make first README.md link point to evy.dev rather than scratch.
- Replace sponsorship red heart emoji with a white one for readability.
Update `make help` awk scripts for multi-line comments on top or rather than
next to target.
Add `/version` endpoint to deployment.
---
Fixes evylang/todo#2
Fixes evylang/todo#3
Fixes evylang/todo#5
Fixes evylang/todo#7
Fixes evylang/todo#8

housekeeping: Improve docs and make help

---

.github/workflows/cicd.yaml
scripts/firebase-deploy

Deploy to prod and now also to stage on merge to main. We do this via
separate GitHub environments: prod and stage and different GitHub actions
job using different `FIREBASE_SERVICE_ACCOUNT_EVY_LANG` secrets wired to
the corresponding firebase prod and stage environments.
When the CI job (not the release job!) is run on `main`, rather than
pull-request, we deploy to https://evystage.dev and its live channel,
rather than the PR preview channel. We don't post preview channels to any
PR. This is done via updates to the firebase-deploy script.
While at it, add a minor, non-functional improvement to sed expression in
firebase-deploy script.
I've setup stage and prod GitHub environments `prod` and `stage` separately via
clicky-clicky-admin, hopefully using the correct Firebase Service Account …

github: Deploy to prod and stage on merge to main

---

.github/workflows/cicd.yaml
.gitignore
Makefile
scripts/firebase-deploy

Simplify deployment process by copying files from `frontend/**` to
`out/firebase/public/**` once only. Copy all firebase configs to out/firebase
and run deployment from there. Clean up various little make things along the
way.

deploy: Simplify deployment process

---

frontend/css/index.css
frontend/index.js
frontend/module/confetti.js
frontend/module/editor.js

Rename YaceEditor to Editor as it is increasingly becoming customized and
tailored to evy. Pull out confetti Easter egg into its own module and remove
dependency on separate CSS file. In last commit re-work confetti Easter egg
for readability.

frontend: Refactor confetti and Yace modules

---

.gitignore
Makefile
e2e/index.test.js
e2e/package-lock.json
e2e/package.json
e2e/playwright.config.js

Initialize end to end testing in top level directory e2e. 
**On CI e2 testing runs against https://evy.dev at the moment!**
Initialize `e2e` node package with
echo '{"private": true}' > e2e/package.json
npm install --save-dev --prefix e2e playwright
npm install --save-dev --prefix e2e @playwright/test@latest
Add `node_modules/` to .gitignore.
Add a minimal `index.test.js` test file that loads the Evy playground `index.html`
page. It runs two tests on it:
- ensure the title is `"Evy | Playground"`
- execute `Run` and ensure the console output contains expected contents.
Setup basic playwright test config that will allow to parametrize the `baseURL`
for tests - it expects a `BASEURL` environment variable and falls back to `https://localhost:8080` by default. For local development run …

e2e: Initialize end to end testing

---

Makefile

Move help text to a separate line as we have updated the awk script to
generate help. This was overlooked in a previous commit.

make: Move help text to a separate line

---

.github/workflows/cicd.yaml
Makefile
firebase/firebase.json
frontend/index.html
scripts/firebase-deploy

Update js and css with hashes in filenames on deployment so that we can have
very long (1 year) cache expiry. If the contents of the file change so will
the hashes and the hashed filenames.
In order for JS files to import correct hashed JS modules, generate importmap
in HTML, e.g.:
<script type="importmap">
{
"imports": {
"./module/editor.js": "./module/editor.11738c78.js"
}
}
</script>
This import statement in index.js
import Editor from "./module/editor.js"
will then load the correct version of `editor.js`.
This PR is complete with regards to creating hashed filenames, however
there is still work left to account for relative CSS and JS file
references in HTML files, such as `"../../css/index.css"`.
Finally, pull it all together by marking file paths matching
`"**/*.*.@(js|css)"`, i.e. …

deploy: Update js and css with hashes in filenames

---

.github/workflows/cicd.yaml
scripts/firebase-deploy

Refactor the generation of the site deployment URLs for the GitHub
environment to remove the chunks of repetitive JSON at the top of the
script and generate the URLs directly without JSON for the live
deployments.
The static chunk of data at the top of the script was a little
in-your-face and seemed rather repetitive, and in hindsight, probably
unnecessary when a simple bit of code could replace it.
Remove the `environment` field from the `ci` GitHub actions job as it
is not needed in that job as deployment was moved to another job. This
reduces some of the "spam" on the PR every time you push.

deploy: Refactor deployment URLs in firebase-deploy

---

.github/workflows/prod.yaml

Checkout the repository on the prod/deploy job so that it can actually
work. This was split off the release job which does the checkout - the
split needed to add the checkout to the new job.

ci: Fix prod workflow to checkout on deploy

---

README.md

Fix the build badge in the README as it is currently orange and says "repo or
workflow not found". We have moved `cicd.yaml` to `stage.yaml` and
`prod.yaml` `prod.yaml` is the only workflow used on `main` so use it for
build status.

docs: Fix build badge on README.md

---

Makefile

Fix the dependency that `check-coverage` and `cover` have on `test`.
This should be `test-go` as the `test` target was changed to `test-go`
in aa0139ed. The circular dependency is due to `make test` depending on
`check-coverage` which then depends on `test`, causing make to emit the
error:
make: Circular check-coverage <- test dependency dropped.

make: Fix circular dependency in Makefile

---

.golangci.yaml
build-tools/firebase-deploy
build-tools/site-gen/main.go
frontend/play/index.html

Rewrite the part of the `firebase-deploy` shell script that generates
the site in Go. To properly track the file renames in arbitrary
directories was going to get messy in shell, so this does it in Go.
The site generator does:
* Optionally rewrite URLs in `.html` files to some top-level paths to
subdomains (discord, docs, learn, and play)
* Optionally rename `.js`, `.css` and `.wasm` files to include a
cache-busting short hash of the content in the filename, and update
any references to the renamed files in any `.html` files. These
references include the stylesheet and javascript HTML references as
well as an embedded javascript importmap and our custom embedded
wasmImport map.
This adds a restriction that the site must not symlink directories -
instead it should create a directory and …

deploy: Rewrite live site generation in Go

---

.github/workflows/stage.yaml
Makefile
build-tools/embed-slim-index.html
docs/usage.md
main.go

Add `evy serve` command, starting a web server, serving the embedded evy website.
This command can also be used to serve the static content of any given directory
with `evy serve --dir`, and export the embedded contents with 
`evy serve export --dir`.
Co-authored-by: Cam Hutchison <camh@xdna.net>

evy: Add serve command

---

README.md
docs/README.md
docs/release-notes/v0.1.0.md
docs/spec.md
docs/syntax_by_example.md
docs/usage.md
main.go

These issues came up as we were revisiting docs for md2html conversion for
https://docs.evy.dev proper. They include:
* Choose better titles as markdown titles will be used in HTML titles
* Use subdomain URLs, e.g. https://docs.evy.dev instead of https://evy.dev/docs
* Updating the `evy` CLI usage docs to include `evy serve`
* Re-arrange docs overview to be targeted at learners (main target group) and less at developers / experienced people

docs: Fix various minor issues in the documentation

---

frontend/play/index.js

We noticed an issue for the following evy example, where the program would
crash with last reporting a NaN for a the move x-coordinate. I have no idea
how this function ever worked, but now it does 😅.
While at it, remove Hash/fragment removal when accessing shared code snippets.
I've found myself wanting to copy that fragment several times now directly
from the address bar so I'm putting it back.
Issue: https://github.com/evylang/evy/issues/264 
Example:
https://play.evy.dev/#content=H4sIAAAAAAAAE3VRTWvDMAy9+1eI7JIuFJLuFug/6G2XjZCD6ziZmWNDPlb730+W0kAGM9iypaenJyvUTevWUcTNKqvlBNndSvWdCdH7CSbpBg2XUgCuAFfcBTRlS++I77i9teuEmPVw025YvqC+wpsQD9PhvRLKW+TKXnpa9xLJvYPR/2gINVaGmE7i7Cb5wCKRCfvVKXaNfp31B4Hp+rlnHFU/Od71MGq3QLllblkUT42ZJJG7y612EE7nioJ/CUxRQWhMCxEPQiRlR3U7lvQF47gptiwppHoYgTOxsTMmZyTnzo6SrE5 …

canvas: Fix Nan in move event

---

pkg/bytecode/code.go
pkg/bytecode/code_test.go
pkg/bytecode/compiler.go
pkg/bytecode/compiler_test.go
pkg/bytecode/doc.go
pkg/bytecode/instructions.go
pkg/bytecode/instructions_test.go
pkg/bytecode/symbol.go
pkg/bytecode/symbol_test.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Create a bytecode package that compiles the parser AST into bytecode
and executes it in a virtual machine. Currently this initial
implementation only supports the simplest evy program; an inferred
type declaration from a constant, followed by an assignment.

bytecode: Create bytecode package

---

.hermit/node/.stylelintrc.json
build-tools/site-gen/main.go
frontend/css/index.css
frontend/css/root.css
frontend/play/css/index.css

Fix ios / Safari 16.2 rendering issues that are related
to older browsers not supporting certain features:
* importmaps
* media queries with `width <= ...`
* nested media queries
---
Fixes https://github.com/evylang/evy/issues/275

frontend: Fix ios / Safari 16.2 rendering issues

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

This change follows on from #274 by adding
compiler support for the remaining
mathematical operators in evy. The compiler
must also understand the `parser.GroupExpression`
to expand expressions inside parenthesis.

bytecode: Implement math operators

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Add opcodes for the boolean literals true and false.
This change lays the groundwork for adding logical and
comparison operators. Cognitive complexity within the
Run function became a problem, so checking push errors
outside the switch statement became necessary for readability.

bytecode: Implement boolean literals

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

This change adds the 'not' and 'minus' unary operators
to the compiler and vm.
Co-authored-by: joshcarp joshcarp@users.noreply.github.com
Co-authored-by: pgmitche pgmitche@users.noreply.github.com

bytecode: Implement unary expressions

---

.github/workflows/prod.yaml
.github/workflows/stage.yaml
Makefile

Change the way playwright is invoked in the Makefile so that specifying
whether to run it in docker is orthogonal to the Makefile target being
invoked.
`make e2e-docker` becomes `make USE_DOCKER=1 e2e`, and `make snaps`
becomes `make snaps USE_DOCKER=1` (note it does not matter where you put
`USE_DOCKER=1` as shown in those two examples).
Now, when a new Makefile target is added for a playwright command, a
second docker version does not need to be added.
Update the CI workflows to use this new method of specifying that
playwright should be run in docker.

make: Generalise running playwright in docker

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

The equality operators are the only operators that can
operate across all evy types. Therefore it makes sense
to utilise the value interface and its Equals function
to generically handle this expression for all evy types.
The alternative is to create separate equality and
inequality opcodes for each evy type, which would
introduce many new opcodes and repeated code in this
package.

bytecode: Implement equality and inequality operators

---

docs/spec.md
frontend/preview/spec.html

Add note to language specification that only arrays of the same type can be
concatenated.

docs: Specify required types array concatenation

---

docs/spec.md
frontend/module/editor.js
frontend/preview/spec.html
pkg/evaluator/evaluator_test.go
pkg/lexer/token.go
pkg/parser/expression.go
pkg/parser/expression_test.go

Allow keywords as map keys after dot expression and in literal initialization
so that the following now parses without error:
m := { "for": "me" "end": "you" }
print m.for m.end
Fixes: https://github.com/evylang/evy/issues/297

parser: Allow keywords as map keys

---

pkg/bytecode/compiler.go
pkg/bytecode/vm_test.go

Add assumption that x = x at the end of every test,
this cuts down on duplicated assertions and makes
tests easier to read. Add some missing assertions
to TestVMGlobals.
Remove initialization to empty list as all tests
pass with nil rather than the empty slice. Rework
vm tests to not use custom asserts and avoid
linter error on duplicated lines. We can now do all
essential testing in vm_test.go via assert.Equal
and assert.NoError.

bytecode: Refactor tests

---

docs/spec.md
frontend/preview/spec.html
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/parser/expression.go
pkg/parser/expression_test.go

Fixes: #292 
Before:
```
print [1 2 3][1:] // [2 3]
print [1 2][1:] // [2]
print [1 2 3][2:2] // []
print [1][1:] // line 5: panic: index out of bounds: 1
```
After:
```
print [1 2 3][1:] // [2 3]
print [1 2][1:] // [2]
print [1 2 3][2:2] // []
print [1][1:] // []
```

evaluator: Allow slice start index to be equal to length

---

pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Fix `any` comparison, ensuring that the underlying types are equal before
comparing the values.
Previously when comparing different underlying types in an `any` a panic occured:
a:any
a = 1
b: any
b = "hello"
print (a == b)
yielded:
evy run foo.evy
panic: internal error: Num.Equals called with non-Num value
Fixes: https://github.com/evylang/evy/issues/298

evaluator: Fix `any` comparison

---

pkg/parser/format.go
pkg/parser/format_test.go

Fix formatting for deeply nested multiline array and literals by tracking
indentation level for multiline literals and arrays.
Fixes: https://github.com/evylang/evy/issues/294

parser: Fix formatting for multiline literals

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Adds comparison operators for numic operands, these will have
distinct opcodes from string comparison operands and avoids
verbose type checking code in the vm. Instead, the compiler
will perform type checks on operands to ensure that unique
opcodes are output depending on the types involved.

bytecode: Implement numeric comparison operators

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Add an internal representation for strings to the package and support
assigning strings. Add opcodes for concatenating and comparing strings.
The compiler takes the burden of type checking the arguments so that
the vm can run an optimised hot path.

bytecode: Implement string literals and operations

---

build-tools/md/tmpl/docs.html.tmpl
frontend/preview/builtins.html
frontend/preview/css/index.css
frontend/preview/index.html
frontend/preview/spec.html
frontend/preview/syntax_by_example.html
frontend/preview/usage.html

Add icons to sidebar footer to reflect to tie the design together with what
we had on the playground (Jason's recommendation).
Fix styling for links with code.
Fixes: https://github.com/evylang/todo/issues/72

docsite: Add icons to sidebar footer

---

build-tools/md/tmpl/docs.html.tmpl
docs/_header.md
frontend/css/root.css
frontend/play/index.html
frontend/preview/builtins.html
frontend/preview/css/index.css
frontend/preview/development/releasing.html
frontend/preview/index.html
frontend/preview/papers/index.html
frontend/preview/release-notes/v0.1.0.html
frontend/preview/spec.html
frontend/preview/syntax_by_example.html
frontend/preview/talks/index.html
frontend/preview/usage.html

Fix various styling issues issues on the docs site:
- center main content
- inline and block `code` styles in light theme
- Spacing between <p> and <pre?
- Footer icons in new tab (also in playground)
Update header contents:
- Link to `/play` rather than `Contributing` <header> section.
- Fix page title in <header> on mobile

docsite: Fix various styling issues

---

pkg/evaluator/evaluator_test.go
pkg/parser/ast.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/type.go

Fix assignability check by tracking type context in Type.Fixed flag: A
variable or expression of composite type has its type field Fixed set to
true. All other types, including literal composite Types have the Type.Fixed
field set to false.
This allows the Type.accept(otherType) method to work without the additional,
previously used `isConst` parameter, which was also imprecise. We can also
remove the `isCompositeConst` and `isConst` functions from the ast.go file.
Additionally rework the `combineTypes()` function to work with the new
Type.Fixed flag.
Add test cases to parser and evaluator package that cover all noted crashes on
nested types.
Issue: https://github.com/evylang/evy/issues/295
---
Fixes #295

parser: Fix assignability check by tracking type context

---

.github/workflows/stage.yaml
Makefile
build-tools/firebase-deploy
firebase/.firebaserc

Add evytest.dev domain as another domain for trying evy things. evystage.dev
gets regularly overridden on merge to master. However, evytest.dev is not yet
included in any regular workflows and more suitable for longer lasting side
development (learning platform?) or previews.

deploy: Add evytest.dev domain

---

e2e/docs/test.js
e2e/play/test.js

Attempt to fix flaky tests, which is really hard as they are not reproducible
on either local run or PR deployments. The await for `networkidle` timed out
a couple of times on the docs tests, so I've attempted to just remove it. It
was added in the first place because the dialog loads an image
asynchronously, but maybe there is no need for an extra wait here.
We've also had a failure in the playground tests where that I saw in the same
way before I added the delay for the animation which should only take 200ms,
but maybe 300ms as enough extra little wiggle room.
---
just deployed manually against evytest.dev and it ran e2e against it which worked as expected, but who knows....

e2e: Attempt to fix flaky tests

---

.github/workflows/prod.yaml
.github/workflows/stage.yaml
Makefile

Fix and simplify deployment which got broken when we introduced evytest.dev.
We now just have a single Makefile target `deploy` that takes the make
variables `CHANNEL` and `ENV`.

deploy: Fix per PR deploys

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Adds support for array literals and array concatenation. Fixed an
issue with assignment where the target and value were swapped, which
would cause the result of any non-trivial assignment to fail. This had
gone unnoticed in the test suite due to the basic (e.g. x = x) usage of
assignments up until this point.

bytecode: Implement arrays

---

frontend/play/index.html
frontend/play/index.js
frontend/play/module/theme.js

Add theme.js for preferred theme to play.evy.dev so that user doesn't have to
reset preferred theme on each visit. This has already been done on
docs.evy.dev, it was just not moved across to the playsite when themes were
added.

playsite: Add theme.js for preferred theme

---

main.go
pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go
pkg/cli/runtime.go

Add support for maps to the compiler, the implementation is very
similar to arrays in https://github.com/evylang/evy/pull/305 but works in key/value pairs.

bytecode: Implement maps

---

pkg/assert/assert.go
pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Adds indexing of maps, arrays and strings. Negative indexing
is supported for arrays and strings. Adds OpSetIndex to
represent an index expression used on the left hand side
of an assignment.

bytecode: Implement index operator

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Support positive and negative slices in the compiler, introduce
OpNone to allow passing empty values for the start or end of a
slice to signal the vm to default the value. The vm will return
a new user error named ErrSlice if the start index of a slice
is greater than the end index.

bytecode: Implement slice expressions 

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/instructions.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Add two new opcodes (`OpJumpOnFalse`, `OpJump`) that give the vm the
ability to skip instructions. Add the `ChangeOperand` function to
`Instructions`, which allows the jump operand to be rewritten after
further instructions have been emitted to the bytecode (this process is
known as backfilling). The alternative to backfilling is a two-pass
compiler, which we discarded as too complex for now.

bytecode: Implement if statements

---

pkg/bytecode/compiler.go
pkg/bytecode/vm_test.go

The bytecode for a while statement is similar to that produced for
an `if`, except that the OpJump points to the start of the
statement and not the end. Break statements are also jumps to
the end of their enclosing loop.

bytecode: Implement while and break statements

---

pkg/evaluator/builtin.go
pkg/evaluator/evaluator.go
pkg/evaluator/value.go

Refactor the `value` interface and the concrete implementations to
remove the `Type()` method from `value`. As evy is a statically typed
language except for `any`, type information should only be needed when
working with `any` values. Removing type information from other values
simplifies the implementation.
There are three steps to the refactor:
* Tidy up some old code in builtins where they used to get concrete
types instead of `anyVal` types but now always get `anyVal` due to the
signature.
* Add a type field to `anyVal` and use only that and the AST type
information where type information is needed.
* Remove the unused `Type()` method and type fields from `arrayVal` and
`mapVal`.

evaluator: Refactor value to remove Type() method

---

pkg/bytecode/value.go
pkg/lexer/token.go
pkg/parser/expression.go
pkg/parser/parser.go

Remove the call to the `String()` method on arguments to the printf
family of functions where those functions would call `String()` anyway,
according to the rules documented in the overview of the `fmt` package.
This makes for less verbose and slightly cleaner code.

Let fmt package call String() on arguments

---

docs/builtins.md
frontend/docs/builtins.html

Update the builtin docs for `join` to say it takes an array of `any`
instead of an array of `string`, as this is what the test case expects.
It makes `join` a bit more useful with less boilerplate to make strings
of non-strings.
Closes: https://github.com/evylang/todo/issues/94

docs: Change join builtin description for []any

---

frontend/docs/index.js
frontend/play/index.html

- Prevent page reload on navigation to self-URL on docs-site
- Open _all_ sidebar links in new tab in playground.
Fixes: https://github.com/evylang/todo/issues/100
Fixes: https://github.com/evylang/todo/issues/99

ux: Tweak playground and docs site

---

docs/spec.md
docs/syntax_by_example.md
frontend/docs/builtins.html
frontend/docs/index.html
frontend/docs/spec.html
frontend/docs/syntax_by_example.html
frontend/docs/usage.html
pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/parser/expression.go
pkg/parser/expression_test.go

Define the `array * num` operator to repeat `array` `num` number of
times. This allows for easy initialisation of variable sized arrays
without needing to use a loop to do so.
Update the spec with a definition of the operator. Update
`syntax_by_example.md` to give some basic examples.
Implement this in the evaluator and the bytecode compiler/vm.
Issue: https://github.com/evylang/todo/issues/101

Define and implement an array repetition operator

---

pkg/bytecode/value.go
pkg/bytecode/vm_test.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Error on non-integer index and slice expressions as it doesn't make much sense
to use it, e.g. in arr[1.1]. We are reusing the nice error message wording
that was introduced in with the ErrBadRepetion. We have also copied the way
we do normalizeSlices indices from evaluator, basing it on normalizeIndex.
Fixes https://github.com/evylang/evy/issues/317

eval: Error on non-integer index and slice expressions

---

pkg/evaluator/evaluator.go
pkg/evaluator/ranger.go

Fix some funny names - "Valal" instead of "Val". It looks like a
previous refactor that made values private was a little off in the
substitutions used to rename some vars.

evaluator: Fix some funny names from previous refactor

---

pkg/evaluator/evaluator.go
pkg/parser/ast.go

Add methods to `StepRange` to return the start, stop and step values,
returning the default value (as a `NumLiteral`) if the value wanted is a
default value (0 for start and 1 for step). Update the evaluator to use
these methods instead of deciding the defaults for itself.
This puts the defaults in one place for when there are multiple
consumers of the AST; the evaluator and the bytecode compiler.

parser/eval: Move StepRange defaults to parser

---

pkg/bytecode/vm_test.go

These assertions are proving laborious to write as the tests in
this package grow more mature and complex. The team has agreed
that since they had add little value for the effort, it is safe
to remove them.

bytecode: Remove bytecode test assertions

---

.goreleaser.yaml
Makefile
build-tools/default-embed/index.html
main-full.go
main.go

Move the build default slim for faster builds with `go build` and also to re-enable
go install evylang.dev/evy@latest
Embeds related to evy.wasm and full build dependency have been moved to
main-full.go which is included via the `-tags=full` flag. Update Makefile and
goreleaser config.

make: Rework full and slim builds

---

pkg/lexer/token.go
pkg/parser/parser_test.go

Report parse error for quoted map keys in map literals.
Before the following code did NOT report an error:
m := {"a": true}
print m
Now it does. The issue was that we accidentally printed `string` for string
literals in the parser which doubled up with the `string` keyword and made
AsIdent() work incorrectly for string literals which it now just passes
through.
Fixes: https://github.com/evylang/evy/issues/338

parser: Report error for quoted map keys

---

firebase/firebase.json

Update config to auto-redirect URLs without extension which so that we can optionally
refer to the spec as
https://docs.evy.dev/spec
rather than
https://docs.evy.dev/spec.html
Docs: https://firebase.google.com/docs/hosting/full-config#control_html_extensions
---
✅ https://docs.evy.dev/spec.html
❌ https://docs.evy.dev/spec
✅ https://evy-lang-stage-docs--344-42d1o10d.web.app/spec
✅ https://evy-lang-stage-docs--344-42d1o10d.web.app/spec.html

firebase: Update config to auto-redirect URLs without extension

---

frontend/docs/index.js

Fix sidebar expansion for "cleanUrls", which is firebase config setting that
allows to load URLs without the ".html" extension. This looks neat in the
address bar but unfortunately broke the sidebar expansion on site reload or
even navigation within the page the a different anchor/hash. With this fix we
have sidebar expand correctly with and without the cleanURL setting.
---
Note how things are broken for:
https://docs.evy.dev/builtins#program-control (sidebar not expanded)
but now works for:
https://docs.evytest.dev/builtins#program-control (sidebar expanded, manually deployed)
and the PR deployemebnt:
https://evy-lang-stage-docs--349-g58dboht.web.app/builtins#program-control

docsite: Fix sidebar expansion for "cleanUrls"

---

docs/builtins.md
frontend/docs/builtins.html

Fix `max` reference example which had a copy-paste error showing the use of
`min`.

docs: Fix max reference

---

docs/builtins.md
examples/human-eval/000.evy
examples/human-eval/002.evy
examples/human-eval/004.evy
examples/human-eval/008.evy
examples/human-eval/020.evy
examples/human-eval/116.evy
examples/human-eval/128.evy
frontend/docs/builtins.html
frontend/docs/index.html
frontend/docs/spec.html
frontend/docs/syntax_by_example.html
frontend/docs/usage.html
frontend/module/highlight.js
frontend/play/samples/tour/math.evy
pkg/evaluator/builtin.go

Add `abs` function for the absolute value of a number. When converting the
human-eval samples I had to manually implement this function one too many
times.

builtins: Add `abs` function

---

pkg/parser/parser.go
pkg/parser/parser_test.go

Improve error message for invalid variadic parameters, where a non-variadic
and a variadic parameters are combined. Previously it said
invalid variadic parameter, must be used with single type
now it says:
variadic parameter cannot be used with other parameters

parser: Improve error message for variadic

---

firebase/firebase.json
frontend/docs/css/index.css
frontend/docs/index.js

* Make anchor navigation via back/forwards/reload work
* Remove firebase' cleanUrl settings because it's opaque and caused other issues
* Fix an issue in `preventReloadOnSelfLink` function

docsite: Fix various minor annoyances

---

docs/builtins.md
frontend/docs/builtins.html
pkg/evaluator/builtin.go

Change the `hsl` function to return a string so that it can be used with the
`color` or the `clear` function.
---
https://evy-lang-stage-play--356-kmaciv5o.web.app/#content=H4sIAAAAAAAAE0vLL1LIVLCyVShKzEtPVTA2M+BSUFBQSM7PyS9S0MgozlHI1ASL5OaXpSpk6hvrmSlAlBSlJpcoGIIFDA0MuFLzUrgAw9CzBU0AAAA=

builtins: Change the hsl function to return a string

---

docs/spec.md
frontend/docs/spec.html
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go

Deep copy array repetitions so that the repetition operator can be used to
initialize 2 or larger dimensional arrays. Previously a reference to inner
arrays was copied which did not allow for array elements to be updated
independently.
Co-authored-by: Cam Hutchison <camh@xdna.net>

evaluator: Deep copy array repetitions

---

frontend/play/samples/animate/bounce.evy
frontend/play/samples/animate/splashtrig.evy
frontend/play/samples/games/tictactoe.evy
frontend/play/samples/interact/ellipse.evy
frontend/play/samples/tour/events.evy

Fix hsl usage in events sample to be composed with the color function.
We have updated hsl to return a string in commit 9b2c83c0 but forgot
to update the example. Let's do it!
While at it, remove all hsl strings in other samples.
---
Compare: https://play.evy.dev/#events
To: https://evy-lang-stage-play--359-whn7zd5c.web.app/#events
use arrow keys to change the color of the dot.

playsite: Fix hsl usage in events sample

---

frontend/play/samples/animate/splashtrig.evy

Revisit the splash of trig example using the new `hsl` builtin and repetition
operator to initialize array. We've reworked the example so that the dots are
now stored in a two dimensional array: an array of rings, where each ring
array holds the dot within the ring. Arguably this is a little easier to
reason about. Additionally, we calculate by default the radius from the orbit
count, and the orbit value. We've also made the animation fully fit within
the canvas.
This changes should make it easier for people playing with it to:
- Add extra dots by adding an extra color
- Add extra orbits by adding an extra speed
I'm not 100% convinced that his is really making things easier to play with
though.
@fcostin - if you have time to look at this, please let me know if this is
still close enough …

playsite: Revisit the splash of trig example

---

pkg/lexer/lexer_test.go
pkg/lexer/token.go

Reserve pkg and import keywords for later use in packages and dependency
management. I really, really, really want to do this eventually.

lexer: Reserve pkg and import keywords

---

examples/human-eval/160.evy
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/ranger.go
pkg/evaluator/scope.go
pkg/evaluator/value.go

Fix assignment of composites with copied references, so that that
a := [1]
b := a
b = [2]
print a b // [a] [b]
now does NOT update the a variable anymore. The assignment now always creates
a new value, rather than updating the existing one.
Fixes: https://github.com/evylang/evy/issues/362

evaluator: Fix assignment of composites with copied references

---

pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/value.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Add OpStepRange and OpIterRange which push the result of evaluating 
the condition of the loop onto the stack to be evaluated by OpJumpOnFalse. 
These operations update the iteration state on the stack and also push the
current value if there is a loop variable so the bytecode can assign that value
to the variable.
Co-authored-by: Cam Hutchison <camh@xdna.net>

bytecode: Implement for loops

---

frontend/play/css/index.css
frontend/play/index.html
frontend/play/index.js

Allow sharing Evy code via playground URLs even if the code cannot be
formatted. This should help with help, e.g. why does this code not work
`<link>`?
It'd be neat to also add sharing to the CLI, e.g. `evy share file.evy`
generating URL or `evy run --url`. We might leave this for later.

playsite: Allow sharing code with parse errors

---

docs/builtins.md
frontend/docs/builtins.html
frontend/docs/index.html
frontend/docs/spec.html
frontend/docs/syntax_by_example.html
frontend/docs/usage.html
frontend/module/highlight.js
pkg/evaluator/builtin.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/value.go
pkg/lexer/lexer.go

Add `repr` function to the evaluator. The function returns a space-separate
string representation of its values that can be copied back in as valid Evy
code for most parts, similar to Python's `repr` function.
Use it in `assert` function so that `assert "2" 2` prints a less confusing
error message.

builtins: Add `repr` function

---

pkg/parser/parser.go
pkg/parser/parser_test.go

Fix confusing error message for "invalid return type: end of line" that
printed and associated the wrong tokens. We have now simplified the message
to `invalid return type` and associate it with the first token of the return
type declaration.

parser: Fix confusing error message

---

frontend/play/index.js

Previously, we've added a special "last" move event for canvas' the
`pointerleave` event. This was in response  to watching my daughter play with
the watermelon sample 🍉 and being confused with what it did when leaving the
mouse left the canvas (https://play.evy.dev/#ellipse - I've noticed kids are
often not that dexterous yet with mice as they use a lot more iPads etc).
Unfortunately, there was no way of capturing in Evy code the condition "mouse
has left canvas" so we added this last synthetic Evy "move" event to be fired
right at the closest edge at 0 y, 100 y, x 0 or x 100 - this allows to test
for leave in the move handler with:
x == 0 or x == 100 or y == 0 or y == 100
Additionally it can be used to draw lines right to the edge.
This seemed like a great compromise, until I recently …

playsite: Fix synthetic leave move event

---

frontend/play/css/index.css
frontend/play/index.html
frontend/play/index.js

Add `editor=none` options to hash in preparation for classroom work: I'd like
to show students a program in execution without giving away how it's
programmed - find out what this thing does by just observing it.
This is a hack. Truth is the playground is ripe for a re-think and re-write,
ideally based around web-components. But that's a big job and this will do
for now. I hope.
---
Try with:
https://evy-lang-stage-play--369-a5xbmcq8.web.app/#sample=welcome&editor=none
https://evy-lang-stage-play--369-a5xbmcq8.web.app/#sample=splashtrig&editor=none

playsite: Add `editor=none` options to hash

---

.golangci.yaml
learn/README.md
learn/cmd/levy/main.go
learn/go.mod
learn/go.sum
learn/pkg/learn/catalog.go
learn/pkg/learn/composition.go
learn/pkg/learn/course.go
learn/pkg/learn/exercise.go
learn/pkg/learn/export.go
learn/pkg/learn/export_test.go
learn/pkg/learn/markdown.go
learn/pkg/learn/testdata/golden/export/all/catalog.json
learn/pkg/learn/unit.go

Add course catalog exporting as single JSON file. Catalog contains all
information to generate a question set for an exercise, quiz or unittest
identified by composite IDs. It also holds the maximumScore achievable for
each course and unit. An exercise has a predefined score of 10. This will
allow for progress tracking as percentage.
Sneak in a couple of preparatory and clean-up commits: fix learn/README.md
update go dependencies and add Name field to some markdown model types.

learn: Add course catalog exporting

---

docs/usage.md
frontend/docs/usage.html
go.mod
learn/pkg/learn/testdata/course1/unit1/exercise-txtar/q-print.txtar
learn/pkg/learn/testdata/golden/export/all/unit1/exercise-txtar/q-print.txtar
learn/pkg/learn/testdata/golden/export/html-no-private-key/unit1/exercise-txtar/q-print.txtar
main.go

Add support for the txtar file format as Evy source input. This will come in
handy for creating course work with multiple choice answers where we need
many small source files.

cli: Support txtar format as input

---

learn/README.md
learn/cmd/levy/main.go
learn/pkg/learn/composition.go
learn/pkg/learn/course.go
learn/pkg/learn/exercise.go
learn/pkg/learn/export.go
learn/pkg/learn/export_test.go
learn/pkg/learn/learn.go
learn/pkg/learn/markdown.go
learn/pkg/learn/question.go
learn/pkg/learn/quiz.go
learn/pkg/learn/renderer.go
learn/pkg/learn/subquestion.go
learn/pkg/learn/tmpl/learn.html.tmpl
learn/pkg/learn/tmpl/self-contained.html.tmpl
learn/pkg/learn/unit.go
learn/pkg/learn/unittest.go

- Generate text output from `//levy:blank` tagged txtar contents
- Render `> [!NOTE]` as a note block
- Split HTML templates into self-contained and learn
- Rename `--with-head-links` flag to `--self-contained`

learn-site: Prepare for initial learn-site generation

---

Makefile
build-tools/firebase-deploy
build-tools/site-gen/main.go
firebase/firebase.json

Use special root path re-write for learn subdomain where we replace
`/lear/PATH` with `/PATH`. This allows for absolute paths without domain used
as links, in particular in sidebar links.

deploy: Use special root path re-write for learn subdomain

---

.gitattributes

Add linguist-generated git attribute for generated .html and .htmlf files.
This is in attempt to make PR reviews more manageable when the templates for
the docs or learn sites get updated.

github: Add linguist-generated git attribute

---

frontend/play/index.js

Improve initialization concurrency, so that we load sample.json, sample content
in parallel to the large evy.wasm file. The difference can be observed in
browser developer tools with network throttling enabled and watching the
waterfall - instead of the previous:
|--- evy.wasm -------------------------|
|-- sample.json -|
|-- welcome.evy -|
we now have
|--- evy.wasm -------------------------|
|-- sample.json -|
|-- welcome.evy -|
This means that for any hash other than #welcome the editor contents are visible
and syntax colored faster.

play-site: Improve initialization concurrency

---

main.go

Create the temporary file for formatting evy source in the same
directory as the source file so that we can rename it over the original
source file if necessary. A rename cannot be across filesystems so the
only valid place for the temp file is in the same directory as the file
that will be overwritten by the rename. Without that, you may get an
error like:
evy: error: hsl.evy: rename /tmp/evy3084141908 hsl.evy: invalid cross-device link

fmt: Create temp file in same dir as source file

---

build-tools/site-gen/main.go
frontend/lab/css/overrides.css
frontend/lab/samples/intro/circles.htmlf
frontend/lab/samples/intro/coords.htmlf
frontend/lab/samples/intro/welcome.htmlf
frontend/lab/samples/loops/hsl.evy

* Improve the HSL example to work with drag and flicker less
* Add a video embed
* Fix broken links to docs sites

lab-site: Improve various unrelated aspects of the first labs

---

docs/builtins.md
frontend/docs/builtins.html
frontend/docs/builtins.htmlf
pkg/cli/svg/runtime.go
pkg/cli/svg/svg.go
pkg/cli/svg/svg_test.go
pkg/evaluator/builtin.go
pkg/wasm/imports.go

Fix `rand` and `sleep` functions to not crash when used with bad arguments: In
the case of rand we ensure the argument is `>= 1`, and in the case of sleep we
ensure we sleep a minimum of 1 millisecond.
Add a minor unrelated typo fix.
This PR has cherry-picked from two other PRs created from forked repo, which
cannot run CI.
Related-pull-request: https://github.com/evylang/evy/pull/412
Related-pull-request: https://github.com/evylang/evy/pull/413
---
@phy1um - I've manually tested it after the fix with `max`, just like you described in
your PR :pray: . 
Code sample 
- ✅ on [PR](https://evy-lang-stage-play--417-0bon79wf.web.app/#content=H4sIAAAAAAAAA0vLL1LIVLCyVShKzEtPVTA0AAEuBQUFheScYjBdUJSZV6KQCWYX56SmFigY6BlAgSFXal4KFwDlzDyURAAAAA==) 
- :boom: on …

builtins: Fix `rand` and `sleep` functions

---

e2e/docs/test.js
e2e/play/test.js

Revert some recent e2e fixes around share dialog snapshot tests. Revert the
removed pixel difference threshhold in one test. However, the previously added
ios tests seem to be ok, so we will leave them in.
It is unclear how these tests passed on PR CI and but do not pass on main CI
despite 3 re-runs. I somewhat consistently could reproduce the issue locally
with:
BASEURL='https://evy.dev' make e2e USE_DOCKER=1
Against localhost / without BASEURL the issue never shows up for me even when
run with docker. However, I had another unrelated issue show up quite
frequently too in the docs tests which seems to be addressed with an extra
wait for network idle. I will keep the docs tests fix in place.
I also suspected that once tests pass once it is harder to get them to fail
again, which would …

e2e: Revert some recent e2e fixes

---

frontend/lab/index.html

Fix regression introduced with the updated share-dialog. I forgot to update the
lab/index.html which did _not_ have a copy button with ID, which caused the
index.js file to throw an exception and abort mid way through initialization.
Not great. I could add e2e tests for the labsite, but this site is so much in
flux at the moment, I'll wait a little longer. Alternatively I could try and
make the JS a little more robust against initialization exceptions, but maybe
erroring early is the right way here.
Fixed for now, labsite e2e on the horizon.
---
btw, this error shows for instance by going to:
https://lab.evy.dev/#hsl
it is kinda weird that it doesn't show with other lab samples, but I can't be
bothered to understand more deeply right now.

labsite: Fix regression

---

frontend/lab/css/overrides.css
frontend/play/css/index.css
frontend/play/index.js

Refactor labsite CSS to use more modern CSS features, especially nesting.
Finally fix the broken looking light-theme sample selection on the playsite and
labsite.
Tweak the scrolling behavior for Next button clicks: we always scroll to top of
notes section. We also use "smooth" scrolling (rather than immediate jumping to
target), which makes it more obvious what's going on. Tested to work on iOS and
MacOS, Chrome, Safari, Firefox. Unfortunately no dice on my Ubuntu laptop with
Smooth scrolling on any browser 🤷‍♀.
Link: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting
---
Deployed at https://lab.evytest.dev

labsite: Tweak CSS and scrolling behavior

---

firebase/.firebaserc

Fix config for gallery prod deployment which accidentally attempted to
deploy to stage - a copy-paste error in .firebaserc.

firebase: Fix config for gallery prod deployment

---

.golangci.yaml
Makefile
build-tools/site-gen/main.go
docs/development/upgrade.md
frontend/docs/development/upgrade.html
frontend/docs/development/upgrade.htmlf
learn/cmd/levy/main.go
learn/pkg/learn/learn.go
main.go

Ignore unwrapped errors in Go `main` packages. We only use Sentinel
errors when provided by packages. Disable err113 linter for main
packages and remove inline `//nolint:` directives.
As I fixed this up I revisited building the go sub-module in `learn/`
and made it consistent in docs and Makefile.

lint: Ignore unwrapped errors in main package

---

.github/workflows/stage.yaml
Makefile

Rework make targets for parallelism, so that we can run
make ci -j $(nproc)
to speed up the CI builds locally and on GitHub Actions. This required a
little of renaming of files used for markdown generation. It also seems
that the node tool prettier and stylelint cannot be installed / run via npx
in parallel.
In a preparatory step add check-uptodate to CI in a fully separate job and
remove it from the test job, to speed up the test CI job. Parallelizing make
does not help with this as `check-uptodate` interferes with testing and needs
to be run sequentially - or on different instances in parallel.
FWIW, hyperfine tells my that my local builds sped up around 2.4 times:
Summary
'make ci -j 16' ran
2.41 ± 0.04 times faster than 'make ci'

make: Rework make targets for parallelism

---

frontend/lab/css/overrides.css
frontend/lab/index.html
frontend/play/index.js

- Make Hint content un-copyable
- Remove copy icon
- Remove extra notes space without editor. There won't be Next buttons (overview only)
- Tweak smooth scrolling offset

labsite: Tweak UI after session with school

---

frontend/module/spa.js

Fix broken PDF links which showed some really strange results on
initial click to Cheat Sheet or Evy Paper. This was caused by link
re-writing in the SPA module. All relative links are re-written on the
docs page to load the .htmlf fragment and display inside the `<main>`
area of the docs. This happens indiscriminately of file type, so the
bug was that we tried to load evy-cheat-sheet.pdff (not the double "f"
at the end). Patch it by using an additional filter condition that only
re-writes relative links that end in `.html`.
Admittedly, this is a bit of a foot-gun, I guess this can happen when
you write all your own tooling. Hopefully the more careful `.html`
file only filtering is the end of this.

docsite: Fix broken PDF links

---

main.go
pkg/bytecode/code.go
pkg/bytecode/compiler.go
pkg/bytecode/symbol.go
pkg/bytecode/symbol_test.go
pkg/bytecode/vm.go
pkg/bytecode/vm_test.go

Add scopes to the compiler so that it can differentiate whether a
variable is global or local. A local variable is one that is not defined
at the top-level of the program - i.e. it is either in a block at the
top-level of the program or in a function (although functions are not
yet implemented in the compiler).
Space is allocated at the top of the stack for the locals needed, with
the stack pointer initialised to start after that. The space allocated
for locals is reused where it can be, for example, when two blocks at
the same level have a local variable, they can share the same space as
they both cannot be in scope at the same time.

bytecode: Implement local variables

---

main-full.go
main.go

Improve version information to use debug.BuildInfo if version string is
not explicitly set by compiler flags. This should provide Version
information when installed via
go install evylang.dev/evy@latest

evy: Improve version information

---

Makefile

Add govulncheck to lint-go target, provided by the Go core team. I just
did the Go developer survey and they asked about whether I know about
it and use it. I did not really know about it, but it seems knowing
about vulnerabilities early is what we want. The current result when
running the check is:
No vulnerabilities found.
Your code is affected by 0 vulnerabilities.
This scan also found 0 vulnerabilities in packages you import and 3
vulnerabilities in modules you require, but your code doesn't appear to call
these vulnerabilities.
Vulnerability #1: GO-2024-3107
Stack exhaustion in Parse in go/build/constraint
More info: https://pkg.go.dev/vuln/GO-2024-3107
Standard library
Found in: stdlib@go1.23
Fixed in: stdlib@go1.23.1
Vulnerability #2: GO-2024-3106
Stack exhaustion in Decoder.Decode …

make: Add govulncheck to lint-go target

---

frontend/css/icons.css
frontend/lab/css/overrides.css
frontend/lab/index.html
frontend/lab/samples/samples.json
frontend/play/css/index.css
frontend/play/index.html
frontend/play/index.js

Add tweaks so the three columns
- Notes
- Editor
- Output
if specified are displayed properly.
Add logic to navigate between them.
---
I've deployed these changes to https://lab.evytest.dev. Ideally tested manually
on mobile or Browser dev tools with <767px width view / responsive enabled.

labsite: Fix mobile three column layout

---

frontend/lab/css/overrides.css
frontend/lab/index.html

Fix link and mobile layout issues and lab.evy.dev. The link to the playground
was incorrect in the sidebar (/playground rather than /play), now fixed.
Additionally shared links on mobile didn't work, the output display didn't show.
CSS tweaked for this too.
---
Test link:
https://lab.evy.dev/#content=H4sIAAAAAAAAAysoyswrUVDySM3JyddRcCpNV1T4MH9i94f5Pf1KXAAmQO5JHQAAAA==
vs
https://lab.evytest.dev/#content=H4sIAAAAAAAAAysoyswrUVDySM3JyddRcCpNV1T4MH9i94f5Pf1KXAAmQO5JHQAAAA==

labsite: Fix link and mobile layout issues

---

LICENSE

Change the license to MIT because it is shorter, simpler and easier to
understand than Apache 2.0 and therefore more aligned with what Evy
tries to do. I have checked with all code contributors that this is
ok.

Change the license to MIT

---

frontend/css/icons.css
frontend/lab/css/overrides.css
frontend/lab/index.html
frontend/play/index.js

Change book-icon to back-icon for mobile: When on mobile only one of
these three screens is showed at a time: Notes, Code, Output. Clicking
the primary button lets you move from Notes -> Code <-> Output. To get
back to the Notes we had a book icon in the top right corner which
caused confusion. The back button is hopefully more logical and also
aligns with the whole screen swipe to to left.

labsite: Change book-icon to back-icon for mobile

---

frontend/play/css/index.css
frontend/play/index.js

When navigating to the next playground sample or lab challenge while on
the output view on mobile, we had this awkward: slide back to notes or
code first, than load new code. It seems more natural and intuitive to
just load the new contents - so for hashChange transition remove
animation by adding and eventually removing a CSS class that sets the
translate transition duration for the main container to 0 seconds.

playsite: Remove slide back transition on navigation

---

frontend/lab/index.html
frontend/play/css/index.css
frontend/play/index.js

Tweak UX for labsite, no major changes
- Use same placeholder content in index.html as in samples/intro/welcome.md
- Always show next/previous sample selection arrows, only disable them
(Jason's suggestion for more stable UI)
- Move back-to-notes button to the left (Jason's suggestion for more obvious UI)
- Make `esc` close sidebar or sample selection modal if open

labsite: Tweak UX

---

frontend/lab/index.html
frontend/play/css/index.css
frontend/play/index.html
frontend/play/index.js

Fix scroll bug where when an Evy program was started with ctrl+enter on
the playsite or labsite and there was an `on key` eventhandler handling
arrow key movements, the Evy code editor **also** started scrolling.
This behavior _only_ occurred when the Evy program was started with
ctrl+enter shortcut, not with the Run button.
---
Compare using by
1. Focus editor
2. ctrl+enter to run program
3. Use :arrow_down: and :arrow_up: when program is running.
4. In first link editor scrolls, in second it should not:
[play.evy.dev](https://play.evy.dev/#content=H4sIAAAAAAAAA5VTS27bMBDd6xQPAgooMOzIdRU3hlWgaIFusigKdF0w5kQmLJMBJdtUV7lCgSJZOr1DkWUP4xPkCMVQUqw07s8LDzlv5r03FJnTmnJMUsRB4DgmcVA1+8zksl4aK3RGDWypyQZGQ2i1FCUFAHB8jPdW6RKaNsiZ2KfVBSpMEQ+Gfss/DyJtYg975NIThGcMhB0S0jJoRT5eylayQoqoQo/Zj/AMwzj2eW89ReQj …

playsite: Fix scroll bug

---

frontend/module/editor.js

Use smarter indentation in Evy web editor.
Whenever a new line is inserted, the editor will automatically:
- preserves indent of current line by default (we already had this).
- increases the indent after block opening keywords
`func` `on` `if` `else` `while` `for` (new).
- updates the current line indent for `end` and `else` keywords:
decreasing the indent if needed (new).
There are many edge cases. This is a best effort improvement. Current
line updating only happens if no selection is active - selection start
and end index are equal.
Fixes: https://github.com/evylang/todo/issues/115
---
The main challenge of this PR is to a bunch of tedious manual testing of the editor.
I will try and write a longer Evy program in the web editor before merging.

editor: Improve Evy web editor to use smarter indentation

---

frontend/css/root.css
frontend/module/editor.js
frontend/play/index.js

Override default ctrl+a browser behavior in lab and playground to select
all editor contents only and not the entire web page.
While at it, make editor highlight a little bit more easily visible.
Fixes: https://github.com/evylang/todo/issues/108

editor: Override default ctrl+a browser behavior

---

README.md
docs/builtins.md
docs/spec.md
frontend/docs/builtins.html
frontend/docs/builtins.htmlf
frontend/docs/index.html
frontend/docs/spec.html
frontend/docs/spec.htmlf
frontend/docs/syntax-by-example.html
frontend/docs/talks-and-papers.html
frontend/docs/usage.html
learn/pkg/learn/markdown.go
learn/pkg/learn/renderer.go
main.go
pkg/cli/runtime.go
pkg/cli/runtime_test.go
pkg/cli/svg/runtime.go
pkg/cli/svg/runtime_test.go
pkg/cli/svg/svg.go
pkg/evaluator/builtin.go
pkg/evaluator/doc.go
pkg/evaluator/evaluator.go
pkg/evaluator/evaluator_test.go
pkg/evaluator/runtime.go
pkg/wasm/imports.go
pkg/wasm/main.go

Rename uses of "runtime" where it refers to the CLI runtime and the browser
runtime to "platform". Runtime usually refers to the thing doing the
running, such as the evaluator or bytecode VM and has started to cause a
little confusion or cumbersome language now that the bytecode VM is being
developed. Initial talk of perhaps targeting micro-controllers as
"platforms" also suggests this should be called platform.
There are still a few uses of the word "runtime" left - these refer to 
things like "runtime errors" where the term still makes sense, as it does
not refer to the Evy abstraction for runtime/platform.
Fix a lint error in `learn/pkg/learn/markdown.go` since golangci-lint wants
to complain about this now.

all: Rename "runtime" to "platform"

---

pkg/evaluator/builtin.go
pkg/parser/ast.go
pkg/parser/expression.go
pkg/parser/expression_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go

Implement niladic function calls without parens, so that the following Evy
code is now valid:
if rand1 > 0.5
print "Heads"
end
print read
print rand1 rand1+10
which reads better than `if (rand1) > 0.5` etc.
Along the way fix typo in name of builtin `"rand1"` (name is used in error
messages only). Improve error message where a function is called and expected
to have a return value.

parser: Implement for niladic function calls without parens

---

Makefile

Targets `docs`, `learn` and `labs` all use prettier which gets installed with
npx --prefix $(NODEPREFIX) -y prettier # ...
Occasionally this seems to fail on CI when run concurrently. Fix by adding an
explicit dependency and prettier installation and a `.WAIT`.

make: Fix prettier installation race
